// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: consumer_events.proto

package network.cow.environment.protocol.v1;

public interface AudioStoppedEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cow.environment.v1.AudioStoppedEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string consumer_id = 1;</code>
   * @return The consumerId.
   */
  java.lang.String getConsumerId();
  /**
   * <code>string consumer_id = 1;</code>
   * @return The bytes for consumerId.
   */
  com.google.protobuf.ByteString
      getConsumerIdBytes();

  /**
   * <code>string id = 2;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 2;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
