// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: consumer_requests.proto

package network.cow.environment.protocol.v1;

public interface AudioDefinitionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cow.environment.v1.AudioDefinition)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string key = 1;</code>
   * @return The key.
   */
  java.lang.String getKey();
  /**
   * <code>string key = 1;</code>
   * @return The bytes for key.
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string url = 3;</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <code>string url = 3;</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <code>string sourceUrl = 4;</code>
   * @return The sourceUrl.
   */
  java.lang.String getSourceUrl();
  /**
   * <code>string sourceUrl = 4;</code>
   * @return The bytes for sourceUrl.
   */
  com.google.protobuf.ByteString
      getSourceUrlBytes();

  /**
   * <code>string reportUrl = 5;</code>
   * @return The reportUrl.
   */
  java.lang.String getReportUrl();
  /**
   * <code>string reportUrl = 5;</code>
   * @return The bytes for reportUrl.
   */
  com.google.protobuf.ByteString
      getReportUrlBytes();

  /**
   * <code>string information = 6;</code>
   * @return The information.
   */
  java.lang.String getInformation();
  /**
   * <code>string information = 6;</code>
   * @return The bytes for information.
   */
  com.google.protobuf.ByteString
      getInformationBytes();
}
