// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service_events.proto

package network.cow.environment.protocol.v1;

public interface ConsumerConnectedEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cow.environment.v1.ConsumerConnectedEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string consumer_id = 1;</code>
   * @return The consumerId.
   */
  java.lang.String getConsumerId();
  /**
   * <code>string consumer_id = 1;</code>
   * @return The bytes for consumerId.
   */
  com.google.protobuf.ByteString
      getConsumerIdBytes();
}
