// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service_events.proto

package network.cow.environment.protocol.v1;

public interface ConsumerChangedInstanceEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cow.environment.v1.ConsumerChangedInstanceEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string consumer_id = 1;</code>
   * @return The consumerId.
   */
  java.lang.String getConsumerId();
  /**
   * <code>string consumer_id = 1;</code>
   * @return The bytes for consumerId.
   */
  com.google.protobuf.ByteString
      getConsumerIdBytes();

  /**
   * <code>string host = 3;</code>
   * @return The host.
   */
  java.lang.String getHost();
  /**
   * <code>string host = 3;</code>
   * @return The bytes for host.
   */
  com.google.protobuf.ByteString
      getHostBytes();

  /**
   * <code>int32 port = 4;</code>
   * @return The port.
   */
  int getPort();
}
