// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: consumer_requests.proto

package network.cow.environment.protocol.v1;

public final class ConsumerRequests {
  private ConsumerRequests() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cow_environment_v1_SetPositionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cow_environment_v1_SetPositionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cow_environment_v1_PlayAudioRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cow_environment_v1_PlayAudioRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cow_environment_v1_UpdateAudioRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cow_environment_v1_UpdateAudioRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cow_environment_v1_FadeAudioRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cow_environment_v1_FadeAudioRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cow_environment_v1_StopAudioRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cow_environment_v1_StopAudioRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cow_environment_v1_Sprite_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cow_environment_v1_Sprite_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cow_environment_v1_Vector_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cow_environment_v1_Vector_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cow_environment_v1_PannerAttributes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cow_environment_v1_PannerAttributes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cow_environment_v1_AudioDefinition_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cow_environment_v1_AudioDefinition_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027consumer_requests.proto\022\022cow.environme" +
      "nt.v1\"\252\001\n\022SetPositionRequest\022\023\n\013consumer" +
      "_id\030\001 \001(\t\022,\n\010position\030\002 \001(\0132\032.cow.enviro" +
      "nment.v1.Vector\022)\n\005front\030\003 \001(\0132\032.cow.env" +
      "ironment.v1.Vector\022&\n\002up\030\004 \001(\0132\032.cow.env" +
      "ironment.v1.Vector\"\353\002\n\020PlayAudioRequest\022" +
      "\023\n\013consumer_id\030\001 \001(\t\022\r\n\003key\030\002 \001(\tH\000\0229\n\nd" +
      "efinition\030\003 \001(\0132#.cow.environment.v1.Aud" +
      "ioDefinitionH\000\022\n\n\002id\030\004 \001(\t\022\016\n\006volume\030\005 \001" +
      "(\001\022\014\n\004rate\030\006 \001(\001\022\014\n\004loop\030\007 \001(\010\022\030\n\020loopFa" +
      "deDuration\030\010 \001(\005\022*\n\006sprite\030\t \001(\0132\032.cow.e" +
      "nvironment.v1.Sprite\022,\n\010position\030\n \001(\0132\032" +
      ".cow.environment.v1.Vector\022>\n\020pannerAttr" +
      "ibutes\030\013 \001(\0132$.cow.environment.v1.Panner" +
      "AttributesB\014\n\nidentifier\"\351\001\n\022UpdateAudio" +
      "Request\022\023\n\013consumer_id\030\001 \001(\t\022\n\n\002id\030\002 \001(\t" +
      "\022\016\n\006volume\030\003 \001(\001\022\014\n\004rate\030\004 \001(\001\022\014\n\004loop\030\005" +
      " \001(\010\022\030\n\020loopFadeDuration\030\006 \001(\005\022,\n\010positi" +
      "on\030\007 \001(\0132\032.cow.environment.v1.Vector\022>\n\020" +
      "pannerAttributes\030\010 \001(\0132$.cow.environment" +
      ".v1.PannerAttributes\"U\n\020FadeAudioRequest" +
      "\022\023\n\013consumer_id\030\001 \001(\t\022\n\n\002id\030\002 \001(\t\022\016\n\006vol" +
      "ume\030\003 \001(\001\022\020\n\010duration\030\004 \001(\005\"E\n\020StopAudio" +
      "Request\022\023\n\013consumer_id\030\001 \001(\t\022\n\n\002id\030\002 \001(\t" +
      "\022\020\n\010duration\030\003 \001(\005\"\"\n\006Sprite\022\014\n\004from\030\001 \001" +
      "(\005\022\n\n\002to\030\002 \001(\005\")\n\006Vector\022\t\n\001x\030\001 \001(\001\022\t\n\001y" +
      "\030\002 \001(\001\022\t\n\001z\030\003 \001(\001\"n\n\020PannerAttributes\022\026\n" +
      "\016distance_model\030\001 \001(\t\022\024\n\014ref_distance\030\002 " +
      "\001(\001\022\026\n\016rolloff_factor\030\003 \001(\001\022\024\n\014max_dista" +
      "nce\030\004 \001(\001\"t\n\017AudioDefinition\022\013\n\003key\030\001 \001(" +
      "\t\022\014\n\004name\030\002 \001(\t\022\013\n\003url\030\003 \001(\t\022\021\n\tsourceUr" +
      "l\030\004 \001(\t\022\021\n\treportUrl\030\005 \001(\t\022\023\n\013informatio" +
      "n\030\006 \001(\tB\'\n#network.cow.environment.proto" +
      "col.v1P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_cow_environment_v1_SetPositionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cow_environment_v1_SetPositionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cow_environment_v1_SetPositionRequest_descriptor,
        new java.lang.String[] { "ConsumerId", "Position", "Front", "Up", });
    internal_static_cow_environment_v1_PlayAudioRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cow_environment_v1_PlayAudioRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cow_environment_v1_PlayAudioRequest_descriptor,
        new java.lang.String[] { "ConsumerId", "Key", "Definition", "Id", "Volume", "Rate", "Loop", "LoopFadeDuration", "Sprite", "Position", "PannerAttributes", "Identifier", });
    internal_static_cow_environment_v1_UpdateAudioRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_cow_environment_v1_UpdateAudioRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cow_environment_v1_UpdateAudioRequest_descriptor,
        new java.lang.String[] { "ConsumerId", "Id", "Volume", "Rate", "Loop", "LoopFadeDuration", "Position", "PannerAttributes", });
    internal_static_cow_environment_v1_FadeAudioRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_cow_environment_v1_FadeAudioRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cow_environment_v1_FadeAudioRequest_descriptor,
        new java.lang.String[] { "ConsumerId", "Id", "Volume", "Duration", });
    internal_static_cow_environment_v1_StopAudioRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_cow_environment_v1_StopAudioRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cow_environment_v1_StopAudioRequest_descriptor,
        new java.lang.String[] { "ConsumerId", "Id", "Duration", });
    internal_static_cow_environment_v1_Sprite_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_cow_environment_v1_Sprite_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cow_environment_v1_Sprite_descriptor,
        new java.lang.String[] { "From", "To", });
    internal_static_cow_environment_v1_Vector_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_cow_environment_v1_Vector_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cow_environment_v1_Vector_descriptor,
        new java.lang.String[] { "X", "Y", "Z", });
    internal_static_cow_environment_v1_PannerAttributes_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_cow_environment_v1_PannerAttributes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cow_environment_v1_PannerAttributes_descriptor,
        new java.lang.String[] { "DistanceModel", "RefDistance", "RolloffFactor", "MaxDistance", });
    internal_static_cow_environment_v1_AudioDefinition_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_cow_environment_v1_AudioDefinition_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cow_environment_v1_AudioDefinition_descriptor,
        new java.lang.String[] { "Key", "Name", "Url", "SourceUrl", "ReportUrl", "Information", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
