// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: consumer_requests.proto

package network.cow.environment.protocol.v1;

public final class ConsumerRequests {
  private ConsumerRequests() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cow_environment_v1_SetPositionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cow_environment_v1_SetPositionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cow_environment_v1_PlayAudioRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cow_environment_v1_PlayAudioRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cow_environment_v1_UpdateAudioRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cow_environment_v1_UpdateAudioRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cow_environment_v1_FadeAudioRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cow_environment_v1_FadeAudioRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cow_environment_v1_StopAudioRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cow_environment_v1_StopAudioRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cow_environment_v1_Sprite_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cow_environment_v1_Sprite_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cow_environment_v1_Vector_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cow_environment_v1_Vector_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cow_environment_v1_PannerAttributes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cow_environment_v1_PannerAttributes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027consumer_requests.proto\022\022cow.environme" +
      "nt.v1\"\252\001\n\022SetPositionRequest\022\023\n\013consumer" +
      "_id\030\001 \001(\t\022,\n\010position\030\002 \001(\0132\032.cow.enviro" +
      "nment.v1.Vector\022)\n\005front\030\003 \001(\0132\032.cow.env" +
      "ironment.v1.Vector\022&\n\002up\030\004 \001(\0132\032.cow.env" +
      "ironment.v1.Vector\"\240\002\n\020PlayAudioRequest\022" +
      "\023\n\013consumer_id\030\001 \001(\t\022\013\n\003key\030\002 \001(\t\022\n\n\002id\030" +
      "\003 \001(\t\022\016\n\006volume\030\004 \001(\001\022\014\n\004rate\030\005 \001(\001\022\014\n\004l" +
      "oop\030\006 \001(\010\022\030\n\020loopFadeDuration\030\007 \001(\005\022*\n\006s" +
      "prite\030\010 \001(\0132\032.cow.environment.v1.Sprite\022" +
      ",\n\010position\030\t \001(\0132\032.cow.environment.v1.V" +
      "ector\022>\n\020pannerAttributes\030\n \001(\0132$.cow.en" +
      "vironment.v1.PannerAttributes\"\351\001\n\022Update" +
      "AudioRequest\022\023\n\013consumer_id\030\001 \001(\t\022\n\n\002id\030" +
      "\002 \001(\t\022\016\n\006volume\030\003 \001(\001\022\014\n\004rate\030\004 \001(\001\022\014\n\004l" +
      "oop\030\005 \001(\010\022\030\n\020loopFadeDuration\030\006 \001(\005\022,\n\010p" +
      "osition\030\007 \001(\0132\032.cow.environment.v1.Vecto" +
      "r\022>\n\020pannerAttributes\030\010 \001(\0132$.cow.enviro" +
      "nment.v1.PannerAttributes\"U\n\020FadeAudioRe" +
      "quest\022\023\n\013consumer_id\030\001 \001(\t\022\n\n\002id\030\002 \001(\t\022\016" +
      "\n\006volume\030\003 \001(\001\022\020\n\010duration\030\004 \001(\005\"E\n\020Stop" +
      "AudioRequest\022\023\n\013consumer_id\030\001 \001(\t\022\n\n\002id\030" +
      "\002 \001(\t\022\020\n\010duration\030\003 \001(\005\"\"\n\006Sprite\022\014\n\004fro" +
      "m\030\001 \001(\005\022\n\n\002to\030\002 \001(\005\")\n\006Vector\022\t\n\001x\030\001 \001(\001" +
      "\022\t\n\001y\030\002 \001(\001\022\t\n\001z\030\003 \001(\001\"n\n\020PannerAttribut" +
      "es\022\026\n\016distance_model\030\001 \001(\t\022\024\n\014ref_distan" +
      "ce\030\002 \001(\001\022\026\n\016rolloff_factor\030\003 \001(\001\022\024\n\014max_" +
      "distance\030\004 \001(\001B\'\n#network.cow.environmen" +
      "t.protocol.v1P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_cow_environment_v1_SetPositionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cow_environment_v1_SetPositionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cow_environment_v1_SetPositionRequest_descriptor,
        new java.lang.String[] { "ConsumerId", "Position", "Front", "Up", });
    internal_static_cow_environment_v1_PlayAudioRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cow_environment_v1_PlayAudioRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cow_environment_v1_PlayAudioRequest_descriptor,
        new java.lang.String[] { "ConsumerId", "Key", "Id", "Volume", "Rate", "Loop", "LoopFadeDuration", "Sprite", "Position", "PannerAttributes", });
    internal_static_cow_environment_v1_UpdateAudioRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_cow_environment_v1_UpdateAudioRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cow_environment_v1_UpdateAudioRequest_descriptor,
        new java.lang.String[] { "ConsumerId", "Id", "Volume", "Rate", "Loop", "LoopFadeDuration", "Position", "PannerAttributes", });
    internal_static_cow_environment_v1_FadeAudioRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_cow_environment_v1_FadeAudioRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cow_environment_v1_FadeAudioRequest_descriptor,
        new java.lang.String[] { "ConsumerId", "Id", "Volume", "Duration", });
    internal_static_cow_environment_v1_StopAudioRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_cow_environment_v1_StopAudioRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cow_environment_v1_StopAudioRequest_descriptor,
        new java.lang.String[] { "ConsumerId", "Id", "Duration", });
    internal_static_cow_environment_v1_Sprite_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_cow_environment_v1_Sprite_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cow_environment_v1_Sprite_descriptor,
        new java.lang.String[] { "From", "To", });
    internal_static_cow_environment_v1_Vector_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_cow_environment_v1_Vector_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cow_environment_v1_Vector_descriptor,
        new java.lang.String[] { "X", "Y", "Z", });
    internal_static_cow_environment_v1_PannerAttributes_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_cow_environment_v1_PannerAttributes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cow_environment_v1_PannerAttributes_descriptor,
        new java.lang.String[] { "DistanceModel", "RefDistance", "RolloffFactor", "MaxDistance", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
