// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: consumer_events.proto

package network.cow.environment.protocol.v1;

public final class ConsumerEvents {
  private ConsumerEvents() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cow_environment_v1_AudioStartedEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cow_environment_v1_AudioStartedEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cow_environment_v1_AudioStoppedEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cow_environment_v1_AudioStoppedEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025consumer_events.proto\022\022cow.environment" +
      ".v1\"4\n\021AudioStartedEvent\022\023\n\013consumer_id\030" +
      "\001 \001(\t\022\n\n\002id\030\002 \001(\t\"4\n\021AudioStoppedEvent\022\023" +
      "\n\013consumer_id\030\001 \001(\t\022\n\n\002id\030\002 \001(\tB\'\n#netwo" +
      "rk.cow.environment.protocol.v1P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_cow_environment_v1_AudioStartedEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cow_environment_v1_AudioStartedEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cow_environment_v1_AudioStartedEvent_descriptor,
        new java.lang.String[] { "ConsumerId", "Id", });
    internal_static_cow_environment_v1_AudioStoppedEvent_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cow_environment_v1_AudioStoppedEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cow_environment_v1_AudioStoppedEvent_descriptor,
        new java.lang.String[] { "ConsumerId", "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
