// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: consumer_requests.proto

package network.cow.environment.protocol.v1;

public interface PannerAttributesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cow.environment.v1.PannerAttributes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string distance_model = 1;</code>
   * @return The distanceModel.
   */
  java.lang.String getDistanceModel();
  /**
   * <code>string distance_model = 1;</code>
   * @return The bytes for distanceModel.
   */
  com.google.protobuf.ByteString
      getDistanceModelBytes();

  /**
   * <code>double ref_distance = 2;</code>
   * @return The refDistance.
   */
  double getRefDistance();

  /**
   * <code>double rolloff_factor = 3;</code>
   * @return The rolloffFactor.
   */
  double getRolloffFactor();

  /**
   * <code>double max_distance = 4;</code>
   * @return The maxDistance.
   */
  double getMaxDistance();
}
