// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: consumer_requests.proto

package network.cow.environment.protocol.v1;

/**
 * Protobuf type {@code cow.environment.v1.PannerAttributes}
 */
public final class PannerAttributes extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cow.environment.v1.PannerAttributes)
    PannerAttributesOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PannerAttributes.newBuilder() to construct.
  private PannerAttributes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PannerAttributes() {
    distanceModel_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PannerAttributes();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PannerAttributes(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            distanceModel_ = s;
            break;
          }
          case 17: {

            refDistance_ = input.readDouble();
            break;
          }
          case 25: {

            rolloffFactor_ = input.readDouble();
            break;
          }
          case 33: {

            maxDistance_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return network.cow.environment.protocol.v1.ConsumerRequests.internal_static_cow_environment_v1_PannerAttributes_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return network.cow.environment.protocol.v1.ConsumerRequests.internal_static_cow_environment_v1_PannerAttributes_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            network.cow.environment.protocol.v1.PannerAttributes.class, network.cow.environment.protocol.v1.PannerAttributes.Builder.class);
  }

  public static final int DISTANCE_MODEL_FIELD_NUMBER = 1;
  private volatile java.lang.Object distanceModel_;
  /**
   * <code>string distance_model = 1;</code>
   * @return The distanceModel.
   */
  @java.lang.Override
  public java.lang.String getDistanceModel() {
    java.lang.Object ref = distanceModel_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      distanceModel_ = s;
      return s;
    }
  }
  /**
   * <code>string distance_model = 1;</code>
   * @return The bytes for distanceModel.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDistanceModelBytes() {
    java.lang.Object ref = distanceModel_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      distanceModel_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REF_DISTANCE_FIELD_NUMBER = 2;
  private double refDistance_;
  /**
   * <code>double ref_distance = 2;</code>
   * @return The refDistance.
   */
  @java.lang.Override
  public double getRefDistance() {
    return refDistance_;
  }

  public static final int ROLLOFF_FACTOR_FIELD_NUMBER = 3;
  private double rolloffFactor_;
  /**
   * <code>double rolloff_factor = 3;</code>
   * @return The rolloffFactor.
   */
  @java.lang.Override
  public double getRolloffFactor() {
    return rolloffFactor_;
  }

  public static final int MAX_DISTANCE_FIELD_NUMBER = 4;
  private double maxDistance_;
  /**
   * <code>double max_distance = 4;</code>
   * @return The maxDistance.
   */
  @java.lang.Override
  public double getMaxDistance() {
    return maxDistance_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getDistanceModelBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, distanceModel_);
    }
    if (refDistance_ != 0D) {
      output.writeDouble(2, refDistance_);
    }
    if (rolloffFactor_ != 0D) {
      output.writeDouble(3, rolloffFactor_);
    }
    if (maxDistance_ != 0D) {
      output.writeDouble(4, maxDistance_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getDistanceModelBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, distanceModel_);
    }
    if (refDistance_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, refDistance_);
    }
    if (rolloffFactor_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, rolloffFactor_);
    }
    if (maxDistance_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, maxDistance_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof network.cow.environment.protocol.v1.PannerAttributes)) {
      return super.equals(obj);
    }
    network.cow.environment.protocol.v1.PannerAttributes other = (network.cow.environment.protocol.v1.PannerAttributes) obj;

    if (!getDistanceModel()
        .equals(other.getDistanceModel())) return false;
    if (java.lang.Double.doubleToLongBits(getRefDistance())
        != java.lang.Double.doubleToLongBits(
            other.getRefDistance())) return false;
    if (java.lang.Double.doubleToLongBits(getRolloffFactor())
        != java.lang.Double.doubleToLongBits(
            other.getRolloffFactor())) return false;
    if (java.lang.Double.doubleToLongBits(getMaxDistance())
        != java.lang.Double.doubleToLongBits(
            other.getMaxDistance())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DISTANCE_MODEL_FIELD_NUMBER;
    hash = (53 * hash) + getDistanceModel().hashCode();
    hash = (37 * hash) + REF_DISTANCE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getRefDistance()));
    hash = (37 * hash) + ROLLOFF_FACTOR_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getRolloffFactor()));
    hash = (37 * hash) + MAX_DISTANCE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getMaxDistance()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static network.cow.environment.protocol.v1.PannerAttributes parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static network.cow.environment.protocol.v1.PannerAttributes parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static network.cow.environment.protocol.v1.PannerAttributes parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static network.cow.environment.protocol.v1.PannerAttributes parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static network.cow.environment.protocol.v1.PannerAttributes parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static network.cow.environment.protocol.v1.PannerAttributes parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static network.cow.environment.protocol.v1.PannerAttributes parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static network.cow.environment.protocol.v1.PannerAttributes parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static network.cow.environment.protocol.v1.PannerAttributes parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static network.cow.environment.protocol.v1.PannerAttributes parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static network.cow.environment.protocol.v1.PannerAttributes parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static network.cow.environment.protocol.v1.PannerAttributes parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(network.cow.environment.protocol.v1.PannerAttributes prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code cow.environment.v1.PannerAttributes}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cow.environment.v1.PannerAttributes)
      network.cow.environment.protocol.v1.PannerAttributesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return network.cow.environment.protocol.v1.ConsumerRequests.internal_static_cow_environment_v1_PannerAttributes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return network.cow.environment.protocol.v1.ConsumerRequests.internal_static_cow_environment_v1_PannerAttributes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              network.cow.environment.protocol.v1.PannerAttributes.class, network.cow.environment.protocol.v1.PannerAttributes.Builder.class);
    }

    // Construct using network.cow.environment.protocol.v1.PannerAttributes.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      distanceModel_ = "";

      refDistance_ = 0D;

      rolloffFactor_ = 0D;

      maxDistance_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return network.cow.environment.protocol.v1.ConsumerRequests.internal_static_cow_environment_v1_PannerAttributes_descriptor;
    }

    @java.lang.Override
    public network.cow.environment.protocol.v1.PannerAttributes getDefaultInstanceForType() {
      return network.cow.environment.protocol.v1.PannerAttributes.getDefaultInstance();
    }

    @java.lang.Override
    public network.cow.environment.protocol.v1.PannerAttributes build() {
      network.cow.environment.protocol.v1.PannerAttributes result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public network.cow.environment.protocol.v1.PannerAttributes buildPartial() {
      network.cow.environment.protocol.v1.PannerAttributes result = new network.cow.environment.protocol.v1.PannerAttributes(this);
      result.distanceModel_ = distanceModel_;
      result.refDistance_ = refDistance_;
      result.rolloffFactor_ = rolloffFactor_;
      result.maxDistance_ = maxDistance_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof network.cow.environment.protocol.v1.PannerAttributes) {
        return mergeFrom((network.cow.environment.protocol.v1.PannerAttributes)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(network.cow.environment.protocol.v1.PannerAttributes other) {
      if (other == network.cow.environment.protocol.v1.PannerAttributes.getDefaultInstance()) return this;
      if (!other.getDistanceModel().isEmpty()) {
        distanceModel_ = other.distanceModel_;
        onChanged();
      }
      if (other.getRefDistance() != 0D) {
        setRefDistance(other.getRefDistance());
      }
      if (other.getRolloffFactor() != 0D) {
        setRolloffFactor(other.getRolloffFactor());
      }
      if (other.getMaxDistance() != 0D) {
        setMaxDistance(other.getMaxDistance());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      network.cow.environment.protocol.v1.PannerAttributes parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (network.cow.environment.protocol.v1.PannerAttributes) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object distanceModel_ = "";
    /**
     * <code>string distance_model = 1;</code>
     * @return The distanceModel.
     */
    public java.lang.String getDistanceModel() {
      java.lang.Object ref = distanceModel_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        distanceModel_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string distance_model = 1;</code>
     * @return The bytes for distanceModel.
     */
    public com.google.protobuf.ByteString
        getDistanceModelBytes() {
      java.lang.Object ref = distanceModel_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        distanceModel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string distance_model = 1;</code>
     * @param value The distanceModel to set.
     * @return This builder for chaining.
     */
    public Builder setDistanceModel(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      distanceModel_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string distance_model = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDistanceModel() {
      
      distanceModel_ = getDefaultInstance().getDistanceModel();
      onChanged();
      return this;
    }
    /**
     * <code>string distance_model = 1;</code>
     * @param value The bytes for distanceModel to set.
     * @return This builder for chaining.
     */
    public Builder setDistanceModelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      distanceModel_ = value;
      onChanged();
      return this;
    }

    private double refDistance_ ;
    /**
     * <code>double ref_distance = 2;</code>
     * @return The refDistance.
     */
    @java.lang.Override
    public double getRefDistance() {
      return refDistance_;
    }
    /**
     * <code>double ref_distance = 2;</code>
     * @param value The refDistance to set.
     * @return This builder for chaining.
     */
    public Builder setRefDistance(double value) {
      
      refDistance_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double ref_distance = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRefDistance() {
      
      refDistance_ = 0D;
      onChanged();
      return this;
    }

    private double rolloffFactor_ ;
    /**
     * <code>double rolloff_factor = 3;</code>
     * @return The rolloffFactor.
     */
    @java.lang.Override
    public double getRolloffFactor() {
      return rolloffFactor_;
    }
    /**
     * <code>double rolloff_factor = 3;</code>
     * @param value The rolloffFactor to set.
     * @return This builder for chaining.
     */
    public Builder setRolloffFactor(double value) {
      
      rolloffFactor_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double rolloff_factor = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRolloffFactor() {
      
      rolloffFactor_ = 0D;
      onChanged();
      return this;
    }

    private double maxDistance_ ;
    /**
     * <code>double max_distance = 4;</code>
     * @return The maxDistance.
     */
    @java.lang.Override
    public double getMaxDistance() {
      return maxDistance_;
    }
    /**
     * <code>double max_distance = 4;</code>
     * @param value The maxDistance to set.
     * @return This builder for chaining.
     */
    public Builder setMaxDistance(double value) {
      
      maxDistance_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double max_distance = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxDistance() {
      
      maxDistance_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:cow.environment.v1.PannerAttributes)
  }

  // @@protoc_insertion_point(class_scope:cow.environment.v1.PannerAttributes)
  private static final network.cow.environment.protocol.v1.PannerAttributes DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new network.cow.environment.protocol.v1.PannerAttributes();
  }

  public static network.cow.environment.protocol.v1.PannerAttributes getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PannerAttributes>
      PARSER = new com.google.protobuf.AbstractParser<PannerAttributes>() {
    @java.lang.Override
    public PannerAttributes parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PannerAttributes(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PannerAttributes> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PannerAttributes> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public network.cow.environment.protocol.v1.PannerAttributes getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

