// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: consumer_requests.proto

package network.cow.environment.protocol.v1;

public interface PlayAudioRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cow.environment.v1.PlayAudioRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string consumer_id = 1;</code>
   * @return The consumerId.
   */
  java.lang.String getConsumerId();
  /**
   * <code>string consumer_id = 1;</code>
   * @return The bytes for consumerId.
   */
  com.google.protobuf.ByteString
      getConsumerIdBytes();

  /**
   * <code>string key = 2;</code>
   * @return Whether the key field is set.
   */
  boolean hasKey();
  /**
   * <code>string key = 2;</code>
   * @return The key.
   */
  java.lang.String getKey();
  /**
   * <code>string key = 2;</code>
   * @return The bytes for key.
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>.cow.environment.v1.AudioDefinition definition = 3;</code>
   * @return Whether the definition field is set.
   */
  boolean hasDefinition();
  /**
   * <code>.cow.environment.v1.AudioDefinition definition = 3;</code>
   * @return The definition.
   */
  network.cow.environment.protocol.v1.AudioDefinition getDefinition();
  /**
   * <code>.cow.environment.v1.AudioDefinition definition = 3;</code>
   */
  network.cow.environment.protocol.v1.AudioDefinitionOrBuilder getDefinitionOrBuilder();

  /**
   * <code>string id = 4;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 4;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>double volume = 5;</code>
   * @return The volume.
   */
  double getVolume();

  /**
   * <code>double rate = 6;</code>
   * @return The rate.
   */
  double getRate();

  /**
   * <code>bool loop = 7;</code>
   * @return The loop.
   */
  boolean getLoop();

  /**
   * <code>int32 loopFadeDuration = 8;</code>
   * @return The loopFadeDuration.
   */
  int getLoopFadeDuration();

  /**
   * <code>.cow.environment.v1.Sprite sprite = 9;</code>
   * @return Whether the sprite field is set.
   */
  boolean hasSprite();
  /**
   * <code>.cow.environment.v1.Sprite sprite = 9;</code>
   * @return The sprite.
   */
  network.cow.environment.protocol.v1.Sprite getSprite();
  /**
   * <code>.cow.environment.v1.Sprite sprite = 9;</code>
   */
  network.cow.environment.protocol.v1.SpriteOrBuilder getSpriteOrBuilder();

  /**
   * <code>.cow.environment.v1.Vector position = 10;</code>
   * @return Whether the position field is set.
   */
  boolean hasPosition();
  /**
   * <code>.cow.environment.v1.Vector position = 10;</code>
   * @return The position.
   */
  network.cow.environment.protocol.v1.Vector getPosition();
  /**
   * <code>.cow.environment.v1.Vector position = 10;</code>
   */
  network.cow.environment.protocol.v1.VectorOrBuilder getPositionOrBuilder();

  /**
   * <code>.cow.environment.v1.PannerAttributes pannerAttributes = 11;</code>
   * @return Whether the pannerAttributes field is set.
   */
  boolean hasPannerAttributes();
  /**
   * <code>.cow.environment.v1.PannerAttributes pannerAttributes = 11;</code>
   * @return The pannerAttributes.
   */
  network.cow.environment.protocol.v1.PannerAttributes getPannerAttributes();
  /**
   * <code>.cow.environment.v1.PannerAttributes pannerAttributes = 11;</code>
   */
  network.cow.environment.protocol.v1.PannerAttributesOrBuilder getPannerAttributesOrBuilder();

  public network.cow.environment.protocol.v1.PlayAudioRequest.IdentifierCase getIdentifierCase();
}
