// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: consumer_requests.proto

package network.cow.environment.protocol.v1;

/**
 * Protobuf type {@code cow.environment.v1.PlayAudioRequest}
 */
public final class PlayAudioRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cow.environment.v1.PlayAudioRequest)
    PlayAudioRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PlayAudioRequest.newBuilder() to construct.
  private PlayAudioRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PlayAudioRequest() {
    consumerId_ = "";
    id_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PlayAudioRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PlayAudioRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            consumerId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            identifierCase_ = 2;
            identifier_ = s;
            break;
          }
          case 26: {
            network.cow.environment.protocol.v1.AudioDefinition.Builder subBuilder = null;
            if (identifierCase_ == 3) {
              subBuilder = ((network.cow.environment.protocol.v1.AudioDefinition) identifier_).toBuilder();
            }
            identifier_ =
                input.readMessage(network.cow.environment.protocol.v1.AudioDefinition.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((network.cow.environment.protocol.v1.AudioDefinition) identifier_);
              identifier_ = subBuilder.buildPartial();
            }
            identifierCase_ = 3;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 41: {

            volume_ = input.readDouble();
            break;
          }
          case 49: {

            rate_ = input.readDouble();
            break;
          }
          case 56: {

            loop_ = input.readBool();
            break;
          }
          case 64: {

            loopFadeDuration_ = input.readInt32();
            break;
          }
          case 74: {
            network.cow.environment.protocol.v1.Sprite.Builder subBuilder = null;
            if (sprite_ != null) {
              subBuilder = sprite_.toBuilder();
            }
            sprite_ = input.readMessage(network.cow.environment.protocol.v1.Sprite.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(sprite_);
              sprite_ = subBuilder.buildPartial();
            }

            break;
          }
          case 82: {
            network.cow.environment.protocol.v1.Vector.Builder subBuilder = null;
            if (position_ != null) {
              subBuilder = position_.toBuilder();
            }
            position_ = input.readMessage(network.cow.environment.protocol.v1.Vector.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(position_);
              position_ = subBuilder.buildPartial();
            }

            break;
          }
          case 90: {
            network.cow.environment.protocol.v1.PannerAttributes.Builder subBuilder = null;
            if (pannerAttributes_ != null) {
              subBuilder = pannerAttributes_.toBuilder();
            }
            pannerAttributes_ = input.readMessage(network.cow.environment.protocol.v1.PannerAttributes.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(pannerAttributes_);
              pannerAttributes_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return network.cow.environment.protocol.v1.ConsumerRequests.internal_static_cow_environment_v1_PlayAudioRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return network.cow.environment.protocol.v1.ConsumerRequests.internal_static_cow_environment_v1_PlayAudioRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            network.cow.environment.protocol.v1.PlayAudioRequest.class, network.cow.environment.protocol.v1.PlayAudioRequest.Builder.class);
  }

  private int identifierCase_ = 0;
  private java.lang.Object identifier_;
  public enum IdentifierCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    KEY(2),
    DEFINITION(3),
    IDENTIFIER_NOT_SET(0);
    private final int value;
    private IdentifierCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static IdentifierCase valueOf(int value) {
      return forNumber(value);
    }

    public static IdentifierCase forNumber(int value) {
      switch (value) {
        case 2: return KEY;
        case 3: return DEFINITION;
        case 0: return IDENTIFIER_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public IdentifierCase
  getIdentifierCase() {
    return IdentifierCase.forNumber(
        identifierCase_);
  }

  public static final int CONSUMER_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object consumerId_;
  /**
   * <code>string consumer_id = 1;</code>
   * @return The consumerId.
   */
  @java.lang.Override
  public java.lang.String getConsumerId() {
    java.lang.Object ref = consumerId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      consumerId_ = s;
      return s;
    }
  }
  /**
   * <code>string consumer_id = 1;</code>
   * @return The bytes for consumerId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getConsumerIdBytes() {
    java.lang.Object ref = consumerId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      consumerId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int KEY_FIELD_NUMBER = 2;
  /**
   * <code>string key = 2;</code>
   * @return Whether the key field is set.
   */
  public boolean hasKey() {
    return identifierCase_ == 2;
  }
  /**
   * <code>string key = 2;</code>
   * @return The key.
   */
  public java.lang.String getKey() {
    java.lang.Object ref = "";
    if (identifierCase_ == 2) {
      ref = identifier_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (identifierCase_ == 2) {
        identifier_ = s;
      }
      return s;
    }
  }
  /**
   * <code>string key = 2;</code>
   * @return The bytes for key.
   */
  public com.google.protobuf.ByteString
      getKeyBytes() {
    java.lang.Object ref = "";
    if (identifierCase_ == 2) {
      ref = identifier_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (identifierCase_ == 2) {
        identifier_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEFINITION_FIELD_NUMBER = 3;
  /**
   * <code>.cow.environment.v1.AudioDefinition definition = 3;</code>
   * @return Whether the definition field is set.
   */
  @java.lang.Override
  public boolean hasDefinition() {
    return identifierCase_ == 3;
  }
  /**
   * <code>.cow.environment.v1.AudioDefinition definition = 3;</code>
   * @return The definition.
   */
  @java.lang.Override
  public network.cow.environment.protocol.v1.AudioDefinition getDefinition() {
    if (identifierCase_ == 3) {
       return (network.cow.environment.protocol.v1.AudioDefinition) identifier_;
    }
    return network.cow.environment.protocol.v1.AudioDefinition.getDefaultInstance();
  }
  /**
   * <code>.cow.environment.v1.AudioDefinition definition = 3;</code>
   */
  @java.lang.Override
  public network.cow.environment.protocol.v1.AudioDefinitionOrBuilder getDefinitionOrBuilder() {
    if (identifierCase_ == 3) {
       return (network.cow.environment.protocol.v1.AudioDefinition) identifier_;
    }
    return network.cow.environment.protocol.v1.AudioDefinition.getDefaultInstance();
  }

  public static final int ID_FIELD_NUMBER = 4;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 4;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 4;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VOLUME_FIELD_NUMBER = 5;
  private double volume_;
  /**
   * <code>double volume = 5;</code>
   * @return The volume.
   */
  @java.lang.Override
  public double getVolume() {
    return volume_;
  }

  public static final int RATE_FIELD_NUMBER = 6;
  private double rate_;
  /**
   * <code>double rate = 6;</code>
   * @return The rate.
   */
  @java.lang.Override
  public double getRate() {
    return rate_;
  }

  public static final int LOOP_FIELD_NUMBER = 7;
  private boolean loop_;
  /**
   * <code>bool loop = 7;</code>
   * @return The loop.
   */
  @java.lang.Override
  public boolean getLoop() {
    return loop_;
  }

  public static final int LOOPFADEDURATION_FIELD_NUMBER = 8;
  private int loopFadeDuration_;
  /**
   * <code>int32 loopFadeDuration = 8;</code>
   * @return The loopFadeDuration.
   */
  @java.lang.Override
  public int getLoopFadeDuration() {
    return loopFadeDuration_;
  }

  public static final int SPRITE_FIELD_NUMBER = 9;
  private network.cow.environment.protocol.v1.Sprite sprite_;
  /**
   * <code>.cow.environment.v1.Sprite sprite = 9;</code>
   * @return Whether the sprite field is set.
   */
  @java.lang.Override
  public boolean hasSprite() {
    return sprite_ != null;
  }
  /**
   * <code>.cow.environment.v1.Sprite sprite = 9;</code>
   * @return The sprite.
   */
  @java.lang.Override
  public network.cow.environment.protocol.v1.Sprite getSprite() {
    return sprite_ == null ? network.cow.environment.protocol.v1.Sprite.getDefaultInstance() : sprite_;
  }
  /**
   * <code>.cow.environment.v1.Sprite sprite = 9;</code>
   */
  @java.lang.Override
  public network.cow.environment.protocol.v1.SpriteOrBuilder getSpriteOrBuilder() {
    return getSprite();
  }

  public static final int POSITION_FIELD_NUMBER = 10;
  private network.cow.environment.protocol.v1.Vector position_;
  /**
   * <code>.cow.environment.v1.Vector position = 10;</code>
   * @return Whether the position field is set.
   */
  @java.lang.Override
  public boolean hasPosition() {
    return position_ != null;
  }
  /**
   * <code>.cow.environment.v1.Vector position = 10;</code>
   * @return The position.
   */
  @java.lang.Override
  public network.cow.environment.protocol.v1.Vector getPosition() {
    return position_ == null ? network.cow.environment.protocol.v1.Vector.getDefaultInstance() : position_;
  }
  /**
   * <code>.cow.environment.v1.Vector position = 10;</code>
   */
  @java.lang.Override
  public network.cow.environment.protocol.v1.VectorOrBuilder getPositionOrBuilder() {
    return getPosition();
  }

  public static final int PANNERATTRIBUTES_FIELD_NUMBER = 11;
  private network.cow.environment.protocol.v1.PannerAttributes pannerAttributes_;
  /**
   * <code>.cow.environment.v1.PannerAttributes pannerAttributes = 11;</code>
   * @return Whether the pannerAttributes field is set.
   */
  @java.lang.Override
  public boolean hasPannerAttributes() {
    return pannerAttributes_ != null;
  }
  /**
   * <code>.cow.environment.v1.PannerAttributes pannerAttributes = 11;</code>
   * @return The pannerAttributes.
   */
  @java.lang.Override
  public network.cow.environment.protocol.v1.PannerAttributes getPannerAttributes() {
    return pannerAttributes_ == null ? network.cow.environment.protocol.v1.PannerAttributes.getDefaultInstance() : pannerAttributes_;
  }
  /**
   * <code>.cow.environment.v1.PannerAttributes pannerAttributes = 11;</code>
   */
  @java.lang.Override
  public network.cow.environment.protocol.v1.PannerAttributesOrBuilder getPannerAttributesOrBuilder() {
    return getPannerAttributes();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getConsumerIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, consumerId_);
    }
    if (identifierCase_ == 2) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, identifier_);
    }
    if (identifierCase_ == 3) {
      output.writeMessage(3, (network.cow.environment.protocol.v1.AudioDefinition) identifier_);
    }
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, id_);
    }
    if (volume_ != 0D) {
      output.writeDouble(5, volume_);
    }
    if (rate_ != 0D) {
      output.writeDouble(6, rate_);
    }
    if (loop_ != false) {
      output.writeBool(7, loop_);
    }
    if (loopFadeDuration_ != 0) {
      output.writeInt32(8, loopFadeDuration_);
    }
    if (sprite_ != null) {
      output.writeMessage(9, getSprite());
    }
    if (position_ != null) {
      output.writeMessage(10, getPosition());
    }
    if (pannerAttributes_ != null) {
      output.writeMessage(11, getPannerAttributes());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getConsumerIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, consumerId_);
    }
    if (identifierCase_ == 2) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, identifier_);
    }
    if (identifierCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (network.cow.environment.protocol.v1.AudioDefinition) identifier_);
    }
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, id_);
    }
    if (volume_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, volume_);
    }
    if (rate_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(6, rate_);
    }
    if (loop_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, loop_);
    }
    if (loopFadeDuration_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, loopFadeDuration_);
    }
    if (sprite_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getSprite());
    }
    if (position_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, getPosition());
    }
    if (pannerAttributes_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, getPannerAttributes());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof network.cow.environment.protocol.v1.PlayAudioRequest)) {
      return super.equals(obj);
    }
    network.cow.environment.protocol.v1.PlayAudioRequest other = (network.cow.environment.protocol.v1.PlayAudioRequest) obj;

    if (!getConsumerId()
        .equals(other.getConsumerId())) return false;
    if (!getId()
        .equals(other.getId())) return false;
    if (java.lang.Double.doubleToLongBits(getVolume())
        != java.lang.Double.doubleToLongBits(
            other.getVolume())) return false;
    if (java.lang.Double.doubleToLongBits(getRate())
        != java.lang.Double.doubleToLongBits(
            other.getRate())) return false;
    if (getLoop()
        != other.getLoop()) return false;
    if (getLoopFadeDuration()
        != other.getLoopFadeDuration()) return false;
    if (hasSprite() != other.hasSprite()) return false;
    if (hasSprite()) {
      if (!getSprite()
          .equals(other.getSprite())) return false;
    }
    if (hasPosition() != other.hasPosition()) return false;
    if (hasPosition()) {
      if (!getPosition()
          .equals(other.getPosition())) return false;
    }
    if (hasPannerAttributes() != other.hasPannerAttributes()) return false;
    if (hasPannerAttributes()) {
      if (!getPannerAttributes()
          .equals(other.getPannerAttributes())) return false;
    }
    if (!getIdentifierCase().equals(other.getIdentifierCase())) return false;
    switch (identifierCase_) {
      case 2:
        if (!getKey()
            .equals(other.getKey())) return false;
        break;
      case 3:
        if (!getDefinition()
            .equals(other.getDefinition())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CONSUMER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getConsumerId().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + VOLUME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getVolume()));
    hash = (37 * hash) + RATE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getRate()));
    hash = (37 * hash) + LOOP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getLoop());
    hash = (37 * hash) + LOOPFADEDURATION_FIELD_NUMBER;
    hash = (53 * hash) + getLoopFadeDuration();
    if (hasSprite()) {
      hash = (37 * hash) + SPRITE_FIELD_NUMBER;
      hash = (53 * hash) + getSprite().hashCode();
    }
    if (hasPosition()) {
      hash = (37 * hash) + POSITION_FIELD_NUMBER;
      hash = (53 * hash) + getPosition().hashCode();
    }
    if (hasPannerAttributes()) {
      hash = (37 * hash) + PANNERATTRIBUTES_FIELD_NUMBER;
      hash = (53 * hash) + getPannerAttributes().hashCode();
    }
    switch (identifierCase_) {
      case 2:
        hash = (37 * hash) + KEY_FIELD_NUMBER;
        hash = (53 * hash) + getKey().hashCode();
        break;
      case 3:
        hash = (37 * hash) + DEFINITION_FIELD_NUMBER;
        hash = (53 * hash) + getDefinition().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static network.cow.environment.protocol.v1.PlayAudioRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static network.cow.environment.protocol.v1.PlayAudioRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static network.cow.environment.protocol.v1.PlayAudioRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static network.cow.environment.protocol.v1.PlayAudioRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static network.cow.environment.protocol.v1.PlayAudioRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static network.cow.environment.protocol.v1.PlayAudioRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static network.cow.environment.protocol.v1.PlayAudioRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static network.cow.environment.protocol.v1.PlayAudioRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static network.cow.environment.protocol.v1.PlayAudioRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static network.cow.environment.protocol.v1.PlayAudioRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static network.cow.environment.protocol.v1.PlayAudioRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static network.cow.environment.protocol.v1.PlayAudioRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(network.cow.environment.protocol.v1.PlayAudioRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code cow.environment.v1.PlayAudioRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cow.environment.v1.PlayAudioRequest)
      network.cow.environment.protocol.v1.PlayAudioRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return network.cow.environment.protocol.v1.ConsumerRequests.internal_static_cow_environment_v1_PlayAudioRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return network.cow.environment.protocol.v1.ConsumerRequests.internal_static_cow_environment_v1_PlayAudioRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              network.cow.environment.protocol.v1.PlayAudioRequest.class, network.cow.environment.protocol.v1.PlayAudioRequest.Builder.class);
    }

    // Construct using network.cow.environment.protocol.v1.PlayAudioRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      consumerId_ = "";

      id_ = "";

      volume_ = 0D;

      rate_ = 0D;

      loop_ = false;

      loopFadeDuration_ = 0;

      if (spriteBuilder_ == null) {
        sprite_ = null;
      } else {
        sprite_ = null;
        spriteBuilder_ = null;
      }
      if (positionBuilder_ == null) {
        position_ = null;
      } else {
        position_ = null;
        positionBuilder_ = null;
      }
      if (pannerAttributesBuilder_ == null) {
        pannerAttributes_ = null;
      } else {
        pannerAttributes_ = null;
        pannerAttributesBuilder_ = null;
      }
      identifierCase_ = 0;
      identifier_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return network.cow.environment.protocol.v1.ConsumerRequests.internal_static_cow_environment_v1_PlayAudioRequest_descriptor;
    }

    @java.lang.Override
    public network.cow.environment.protocol.v1.PlayAudioRequest getDefaultInstanceForType() {
      return network.cow.environment.protocol.v1.PlayAudioRequest.getDefaultInstance();
    }

    @java.lang.Override
    public network.cow.environment.protocol.v1.PlayAudioRequest build() {
      network.cow.environment.protocol.v1.PlayAudioRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public network.cow.environment.protocol.v1.PlayAudioRequest buildPartial() {
      network.cow.environment.protocol.v1.PlayAudioRequest result = new network.cow.environment.protocol.v1.PlayAudioRequest(this);
      result.consumerId_ = consumerId_;
      if (identifierCase_ == 2) {
        result.identifier_ = identifier_;
      }
      if (identifierCase_ == 3) {
        if (definitionBuilder_ == null) {
          result.identifier_ = identifier_;
        } else {
          result.identifier_ = definitionBuilder_.build();
        }
      }
      result.id_ = id_;
      result.volume_ = volume_;
      result.rate_ = rate_;
      result.loop_ = loop_;
      result.loopFadeDuration_ = loopFadeDuration_;
      if (spriteBuilder_ == null) {
        result.sprite_ = sprite_;
      } else {
        result.sprite_ = spriteBuilder_.build();
      }
      if (positionBuilder_ == null) {
        result.position_ = position_;
      } else {
        result.position_ = positionBuilder_.build();
      }
      if (pannerAttributesBuilder_ == null) {
        result.pannerAttributes_ = pannerAttributes_;
      } else {
        result.pannerAttributes_ = pannerAttributesBuilder_.build();
      }
      result.identifierCase_ = identifierCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof network.cow.environment.protocol.v1.PlayAudioRequest) {
        return mergeFrom((network.cow.environment.protocol.v1.PlayAudioRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(network.cow.environment.protocol.v1.PlayAudioRequest other) {
      if (other == network.cow.environment.protocol.v1.PlayAudioRequest.getDefaultInstance()) return this;
      if (!other.getConsumerId().isEmpty()) {
        consumerId_ = other.consumerId_;
        onChanged();
      }
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (other.getVolume() != 0D) {
        setVolume(other.getVolume());
      }
      if (other.getRate() != 0D) {
        setRate(other.getRate());
      }
      if (other.getLoop() != false) {
        setLoop(other.getLoop());
      }
      if (other.getLoopFadeDuration() != 0) {
        setLoopFadeDuration(other.getLoopFadeDuration());
      }
      if (other.hasSprite()) {
        mergeSprite(other.getSprite());
      }
      if (other.hasPosition()) {
        mergePosition(other.getPosition());
      }
      if (other.hasPannerAttributes()) {
        mergePannerAttributes(other.getPannerAttributes());
      }
      switch (other.getIdentifierCase()) {
        case KEY: {
          identifierCase_ = 2;
          identifier_ = other.identifier_;
          onChanged();
          break;
        }
        case DEFINITION: {
          mergeDefinition(other.getDefinition());
          break;
        }
        case IDENTIFIER_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      network.cow.environment.protocol.v1.PlayAudioRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (network.cow.environment.protocol.v1.PlayAudioRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int identifierCase_ = 0;
    private java.lang.Object identifier_;
    public IdentifierCase
        getIdentifierCase() {
      return IdentifierCase.forNumber(
          identifierCase_);
    }

    public Builder clearIdentifier() {
      identifierCase_ = 0;
      identifier_ = null;
      onChanged();
      return this;
    }


    private java.lang.Object consumerId_ = "";
    /**
     * <code>string consumer_id = 1;</code>
     * @return The consumerId.
     */
    public java.lang.String getConsumerId() {
      java.lang.Object ref = consumerId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        consumerId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string consumer_id = 1;</code>
     * @return The bytes for consumerId.
     */
    public com.google.protobuf.ByteString
        getConsumerIdBytes() {
      java.lang.Object ref = consumerId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        consumerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string consumer_id = 1;</code>
     * @param value The consumerId to set.
     * @return This builder for chaining.
     */
    public Builder setConsumerId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      consumerId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string consumer_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearConsumerId() {
      
      consumerId_ = getDefaultInstance().getConsumerId();
      onChanged();
      return this;
    }
    /**
     * <code>string consumer_id = 1;</code>
     * @param value The bytes for consumerId to set.
     * @return This builder for chaining.
     */
    public Builder setConsumerIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      consumerId_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string key = 2;</code>
     * @return Whether the key field is set.
     */
    @java.lang.Override
    public boolean hasKey() {
      return identifierCase_ == 2;
    }
    /**
     * <code>string key = 2;</code>
     * @return The key.
     */
    @java.lang.Override
    public java.lang.String getKey() {
      java.lang.Object ref = "";
      if (identifierCase_ == 2) {
        ref = identifier_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (identifierCase_ == 2) {
          identifier_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string key = 2;</code>
     * @return The bytes for key.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = "";
      if (identifierCase_ == 2) {
        ref = identifier_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (identifierCase_ == 2) {
          identifier_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string key = 2;</code>
     * @param value The key to set.
     * @return This builder for chaining.
     */
    public Builder setKey(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  identifierCase_ = 2;
      identifier_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string key = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearKey() {
      if (identifierCase_ == 2) {
        identifierCase_ = 0;
        identifier_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <code>string key = 2;</code>
     * @param value The bytes for key to set.
     * @return This builder for chaining.
     */
    public Builder setKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      identifierCase_ = 2;
      identifier_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        network.cow.environment.protocol.v1.AudioDefinition, network.cow.environment.protocol.v1.AudioDefinition.Builder, network.cow.environment.protocol.v1.AudioDefinitionOrBuilder> definitionBuilder_;
    /**
     * <code>.cow.environment.v1.AudioDefinition definition = 3;</code>
     * @return Whether the definition field is set.
     */
    @java.lang.Override
    public boolean hasDefinition() {
      return identifierCase_ == 3;
    }
    /**
     * <code>.cow.environment.v1.AudioDefinition definition = 3;</code>
     * @return The definition.
     */
    @java.lang.Override
    public network.cow.environment.protocol.v1.AudioDefinition getDefinition() {
      if (definitionBuilder_ == null) {
        if (identifierCase_ == 3) {
          return (network.cow.environment.protocol.v1.AudioDefinition) identifier_;
        }
        return network.cow.environment.protocol.v1.AudioDefinition.getDefaultInstance();
      } else {
        if (identifierCase_ == 3) {
          return definitionBuilder_.getMessage();
        }
        return network.cow.environment.protocol.v1.AudioDefinition.getDefaultInstance();
      }
    }
    /**
     * <code>.cow.environment.v1.AudioDefinition definition = 3;</code>
     */
    public Builder setDefinition(network.cow.environment.protocol.v1.AudioDefinition value) {
      if (definitionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        identifier_ = value;
        onChanged();
      } else {
        definitionBuilder_.setMessage(value);
      }
      identifierCase_ = 3;
      return this;
    }
    /**
     * <code>.cow.environment.v1.AudioDefinition definition = 3;</code>
     */
    public Builder setDefinition(
        network.cow.environment.protocol.v1.AudioDefinition.Builder builderForValue) {
      if (definitionBuilder_ == null) {
        identifier_ = builderForValue.build();
        onChanged();
      } else {
        definitionBuilder_.setMessage(builderForValue.build());
      }
      identifierCase_ = 3;
      return this;
    }
    /**
     * <code>.cow.environment.v1.AudioDefinition definition = 3;</code>
     */
    public Builder mergeDefinition(network.cow.environment.protocol.v1.AudioDefinition value) {
      if (definitionBuilder_ == null) {
        if (identifierCase_ == 3 &&
            identifier_ != network.cow.environment.protocol.v1.AudioDefinition.getDefaultInstance()) {
          identifier_ = network.cow.environment.protocol.v1.AudioDefinition.newBuilder((network.cow.environment.protocol.v1.AudioDefinition) identifier_)
              .mergeFrom(value).buildPartial();
        } else {
          identifier_ = value;
        }
        onChanged();
      } else {
        if (identifierCase_ == 3) {
          definitionBuilder_.mergeFrom(value);
        }
        definitionBuilder_.setMessage(value);
      }
      identifierCase_ = 3;
      return this;
    }
    /**
     * <code>.cow.environment.v1.AudioDefinition definition = 3;</code>
     */
    public Builder clearDefinition() {
      if (definitionBuilder_ == null) {
        if (identifierCase_ == 3) {
          identifierCase_ = 0;
          identifier_ = null;
          onChanged();
        }
      } else {
        if (identifierCase_ == 3) {
          identifierCase_ = 0;
          identifier_ = null;
        }
        definitionBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.cow.environment.v1.AudioDefinition definition = 3;</code>
     */
    public network.cow.environment.protocol.v1.AudioDefinition.Builder getDefinitionBuilder() {
      return getDefinitionFieldBuilder().getBuilder();
    }
    /**
     * <code>.cow.environment.v1.AudioDefinition definition = 3;</code>
     */
    @java.lang.Override
    public network.cow.environment.protocol.v1.AudioDefinitionOrBuilder getDefinitionOrBuilder() {
      if ((identifierCase_ == 3) && (definitionBuilder_ != null)) {
        return definitionBuilder_.getMessageOrBuilder();
      } else {
        if (identifierCase_ == 3) {
          return (network.cow.environment.protocol.v1.AudioDefinition) identifier_;
        }
        return network.cow.environment.protocol.v1.AudioDefinition.getDefaultInstance();
      }
    }
    /**
     * <code>.cow.environment.v1.AudioDefinition definition = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        network.cow.environment.protocol.v1.AudioDefinition, network.cow.environment.protocol.v1.AudioDefinition.Builder, network.cow.environment.protocol.v1.AudioDefinitionOrBuilder> 
        getDefinitionFieldBuilder() {
      if (definitionBuilder_ == null) {
        if (!(identifierCase_ == 3)) {
          identifier_ = network.cow.environment.protocol.v1.AudioDefinition.getDefaultInstance();
        }
        definitionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            network.cow.environment.protocol.v1.AudioDefinition, network.cow.environment.protocol.v1.AudioDefinition.Builder, network.cow.environment.protocol.v1.AudioDefinitionOrBuilder>(
                (network.cow.environment.protocol.v1.AudioDefinition) identifier_,
                getParentForChildren(),
                isClean());
        identifier_ = null;
      }
      identifierCase_ = 3;
      onChanged();;
      return definitionBuilder_;
    }

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 4;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 4;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 4;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 4;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private double volume_ ;
    /**
     * <code>double volume = 5;</code>
     * @return The volume.
     */
    @java.lang.Override
    public double getVolume() {
      return volume_;
    }
    /**
     * <code>double volume = 5;</code>
     * @param value The volume to set.
     * @return This builder for chaining.
     */
    public Builder setVolume(double value) {
      
      volume_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double volume = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearVolume() {
      
      volume_ = 0D;
      onChanged();
      return this;
    }

    private double rate_ ;
    /**
     * <code>double rate = 6;</code>
     * @return The rate.
     */
    @java.lang.Override
    public double getRate() {
      return rate_;
    }
    /**
     * <code>double rate = 6;</code>
     * @param value The rate to set.
     * @return This builder for chaining.
     */
    public Builder setRate(double value) {
      
      rate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double rate = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearRate() {
      
      rate_ = 0D;
      onChanged();
      return this;
    }

    private boolean loop_ ;
    /**
     * <code>bool loop = 7;</code>
     * @return The loop.
     */
    @java.lang.Override
    public boolean getLoop() {
      return loop_;
    }
    /**
     * <code>bool loop = 7;</code>
     * @param value The loop to set.
     * @return This builder for chaining.
     */
    public Builder setLoop(boolean value) {
      
      loop_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool loop = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearLoop() {
      
      loop_ = false;
      onChanged();
      return this;
    }

    private int loopFadeDuration_ ;
    /**
     * <code>int32 loopFadeDuration = 8;</code>
     * @return The loopFadeDuration.
     */
    @java.lang.Override
    public int getLoopFadeDuration() {
      return loopFadeDuration_;
    }
    /**
     * <code>int32 loopFadeDuration = 8;</code>
     * @param value The loopFadeDuration to set.
     * @return This builder for chaining.
     */
    public Builder setLoopFadeDuration(int value) {
      
      loopFadeDuration_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 loopFadeDuration = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearLoopFadeDuration() {
      
      loopFadeDuration_ = 0;
      onChanged();
      return this;
    }

    private network.cow.environment.protocol.v1.Sprite sprite_;
    private com.google.protobuf.SingleFieldBuilderV3<
        network.cow.environment.protocol.v1.Sprite, network.cow.environment.protocol.v1.Sprite.Builder, network.cow.environment.protocol.v1.SpriteOrBuilder> spriteBuilder_;
    /**
     * <code>.cow.environment.v1.Sprite sprite = 9;</code>
     * @return Whether the sprite field is set.
     */
    public boolean hasSprite() {
      return spriteBuilder_ != null || sprite_ != null;
    }
    /**
     * <code>.cow.environment.v1.Sprite sprite = 9;</code>
     * @return The sprite.
     */
    public network.cow.environment.protocol.v1.Sprite getSprite() {
      if (spriteBuilder_ == null) {
        return sprite_ == null ? network.cow.environment.protocol.v1.Sprite.getDefaultInstance() : sprite_;
      } else {
        return spriteBuilder_.getMessage();
      }
    }
    /**
     * <code>.cow.environment.v1.Sprite sprite = 9;</code>
     */
    public Builder setSprite(network.cow.environment.protocol.v1.Sprite value) {
      if (spriteBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        sprite_ = value;
        onChanged();
      } else {
        spriteBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.cow.environment.v1.Sprite sprite = 9;</code>
     */
    public Builder setSprite(
        network.cow.environment.protocol.v1.Sprite.Builder builderForValue) {
      if (spriteBuilder_ == null) {
        sprite_ = builderForValue.build();
        onChanged();
      } else {
        spriteBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.cow.environment.v1.Sprite sprite = 9;</code>
     */
    public Builder mergeSprite(network.cow.environment.protocol.v1.Sprite value) {
      if (spriteBuilder_ == null) {
        if (sprite_ != null) {
          sprite_ =
            network.cow.environment.protocol.v1.Sprite.newBuilder(sprite_).mergeFrom(value).buildPartial();
        } else {
          sprite_ = value;
        }
        onChanged();
      } else {
        spriteBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.cow.environment.v1.Sprite sprite = 9;</code>
     */
    public Builder clearSprite() {
      if (spriteBuilder_ == null) {
        sprite_ = null;
        onChanged();
      } else {
        sprite_ = null;
        spriteBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.cow.environment.v1.Sprite sprite = 9;</code>
     */
    public network.cow.environment.protocol.v1.Sprite.Builder getSpriteBuilder() {
      
      onChanged();
      return getSpriteFieldBuilder().getBuilder();
    }
    /**
     * <code>.cow.environment.v1.Sprite sprite = 9;</code>
     */
    public network.cow.environment.protocol.v1.SpriteOrBuilder getSpriteOrBuilder() {
      if (spriteBuilder_ != null) {
        return spriteBuilder_.getMessageOrBuilder();
      } else {
        return sprite_ == null ?
            network.cow.environment.protocol.v1.Sprite.getDefaultInstance() : sprite_;
      }
    }
    /**
     * <code>.cow.environment.v1.Sprite sprite = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        network.cow.environment.protocol.v1.Sprite, network.cow.environment.protocol.v1.Sprite.Builder, network.cow.environment.protocol.v1.SpriteOrBuilder> 
        getSpriteFieldBuilder() {
      if (spriteBuilder_ == null) {
        spriteBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            network.cow.environment.protocol.v1.Sprite, network.cow.environment.protocol.v1.Sprite.Builder, network.cow.environment.protocol.v1.SpriteOrBuilder>(
                getSprite(),
                getParentForChildren(),
                isClean());
        sprite_ = null;
      }
      return spriteBuilder_;
    }

    private network.cow.environment.protocol.v1.Vector position_;
    private com.google.protobuf.SingleFieldBuilderV3<
        network.cow.environment.protocol.v1.Vector, network.cow.environment.protocol.v1.Vector.Builder, network.cow.environment.protocol.v1.VectorOrBuilder> positionBuilder_;
    /**
     * <code>.cow.environment.v1.Vector position = 10;</code>
     * @return Whether the position field is set.
     */
    public boolean hasPosition() {
      return positionBuilder_ != null || position_ != null;
    }
    /**
     * <code>.cow.environment.v1.Vector position = 10;</code>
     * @return The position.
     */
    public network.cow.environment.protocol.v1.Vector getPosition() {
      if (positionBuilder_ == null) {
        return position_ == null ? network.cow.environment.protocol.v1.Vector.getDefaultInstance() : position_;
      } else {
        return positionBuilder_.getMessage();
      }
    }
    /**
     * <code>.cow.environment.v1.Vector position = 10;</code>
     */
    public Builder setPosition(network.cow.environment.protocol.v1.Vector value) {
      if (positionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        position_ = value;
        onChanged();
      } else {
        positionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.cow.environment.v1.Vector position = 10;</code>
     */
    public Builder setPosition(
        network.cow.environment.protocol.v1.Vector.Builder builderForValue) {
      if (positionBuilder_ == null) {
        position_ = builderForValue.build();
        onChanged();
      } else {
        positionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.cow.environment.v1.Vector position = 10;</code>
     */
    public Builder mergePosition(network.cow.environment.protocol.v1.Vector value) {
      if (positionBuilder_ == null) {
        if (position_ != null) {
          position_ =
            network.cow.environment.protocol.v1.Vector.newBuilder(position_).mergeFrom(value).buildPartial();
        } else {
          position_ = value;
        }
        onChanged();
      } else {
        positionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.cow.environment.v1.Vector position = 10;</code>
     */
    public Builder clearPosition() {
      if (positionBuilder_ == null) {
        position_ = null;
        onChanged();
      } else {
        position_ = null;
        positionBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.cow.environment.v1.Vector position = 10;</code>
     */
    public network.cow.environment.protocol.v1.Vector.Builder getPositionBuilder() {
      
      onChanged();
      return getPositionFieldBuilder().getBuilder();
    }
    /**
     * <code>.cow.environment.v1.Vector position = 10;</code>
     */
    public network.cow.environment.protocol.v1.VectorOrBuilder getPositionOrBuilder() {
      if (positionBuilder_ != null) {
        return positionBuilder_.getMessageOrBuilder();
      } else {
        return position_ == null ?
            network.cow.environment.protocol.v1.Vector.getDefaultInstance() : position_;
      }
    }
    /**
     * <code>.cow.environment.v1.Vector position = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        network.cow.environment.protocol.v1.Vector, network.cow.environment.protocol.v1.Vector.Builder, network.cow.environment.protocol.v1.VectorOrBuilder> 
        getPositionFieldBuilder() {
      if (positionBuilder_ == null) {
        positionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            network.cow.environment.protocol.v1.Vector, network.cow.environment.protocol.v1.Vector.Builder, network.cow.environment.protocol.v1.VectorOrBuilder>(
                getPosition(),
                getParentForChildren(),
                isClean());
        position_ = null;
      }
      return positionBuilder_;
    }

    private network.cow.environment.protocol.v1.PannerAttributes pannerAttributes_;
    private com.google.protobuf.SingleFieldBuilderV3<
        network.cow.environment.protocol.v1.PannerAttributes, network.cow.environment.protocol.v1.PannerAttributes.Builder, network.cow.environment.protocol.v1.PannerAttributesOrBuilder> pannerAttributesBuilder_;
    /**
     * <code>.cow.environment.v1.PannerAttributes pannerAttributes = 11;</code>
     * @return Whether the pannerAttributes field is set.
     */
    public boolean hasPannerAttributes() {
      return pannerAttributesBuilder_ != null || pannerAttributes_ != null;
    }
    /**
     * <code>.cow.environment.v1.PannerAttributes pannerAttributes = 11;</code>
     * @return The pannerAttributes.
     */
    public network.cow.environment.protocol.v1.PannerAttributes getPannerAttributes() {
      if (pannerAttributesBuilder_ == null) {
        return pannerAttributes_ == null ? network.cow.environment.protocol.v1.PannerAttributes.getDefaultInstance() : pannerAttributes_;
      } else {
        return pannerAttributesBuilder_.getMessage();
      }
    }
    /**
     * <code>.cow.environment.v1.PannerAttributes pannerAttributes = 11;</code>
     */
    public Builder setPannerAttributes(network.cow.environment.protocol.v1.PannerAttributes value) {
      if (pannerAttributesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pannerAttributes_ = value;
        onChanged();
      } else {
        pannerAttributesBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.cow.environment.v1.PannerAttributes pannerAttributes = 11;</code>
     */
    public Builder setPannerAttributes(
        network.cow.environment.protocol.v1.PannerAttributes.Builder builderForValue) {
      if (pannerAttributesBuilder_ == null) {
        pannerAttributes_ = builderForValue.build();
        onChanged();
      } else {
        pannerAttributesBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.cow.environment.v1.PannerAttributes pannerAttributes = 11;</code>
     */
    public Builder mergePannerAttributes(network.cow.environment.protocol.v1.PannerAttributes value) {
      if (pannerAttributesBuilder_ == null) {
        if (pannerAttributes_ != null) {
          pannerAttributes_ =
            network.cow.environment.protocol.v1.PannerAttributes.newBuilder(pannerAttributes_).mergeFrom(value).buildPartial();
        } else {
          pannerAttributes_ = value;
        }
        onChanged();
      } else {
        pannerAttributesBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.cow.environment.v1.PannerAttributes pannerAttributes = 11;</code>
     */
    public Builder clearPannerAttributes() {
      if (pannerAttributesBuilder_ == null) {
        pannerAttributes_ = null;
        onChanged();
      } else {
        pannerAttributes_ = null;
        pannerAttributesBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.cow.environment.v1.PannerAttributes pannerAttributes = 11;</code>
     */
    public network.cow.environment.protocol.v1.PannerAttributes.Builder getPannerAttributesBuilder() {
      
      onChanged();
      return getPannerAttributesFieldBuilder().getBuilder();
    }
    /**
     * <code>.cow.environment.v1.PannerAttributes pannerAttributes = 11;</code>
     */
    public network.cow.environment.protocol.v1.PannerAttributesOrBuilder getPannerAttributesOrBuilder() {
      if (pannerAttributesBuilder_ != null) {
        return pannerAttributesBuilder_.getMessageOrBuilder();
      } else {
        return pannerAttributes_ == null ?
            network.cow.environment.protocol.v1.PannerAttributes.getDefaultInstance() : pannerAttributes_;
      }
    }
    /**
     * <code>.cow.environment.v1.PannerAttributes pannerAttributes = 11;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        network.cow.environment.protocol.v1.PannerAttributes, network.cow.environment.protocol.v1.PannerAttributes.Builder, network.cow.environment.protocol.v1.PannerAttributesOrBuilder> 
        getPannerAttributesFieldBuilder() {
      if (pannerAttributesBuilder_ == null) {
        pannerAttributesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            network.cow.environment.protocol.v1.PannerAttributes, network.cow.environment.protocol.v1.PannerAttributes.Builder, network.cow.environment.protocol.v1.PannerAttributesOrBuilder>(
                getPannerAttributes(),
                getParentForChildren(),
                isClean());
        pannerAttributes_ = null;
      }
      return pannerAttributesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:cow.environment.v1.PlayAudioRequest)
  }

  // @@protoc_insertion_point(class_scope:cow.environment.v1.PlayAudioRequest)
  private static final network.cow.environment.protocol.v1.PlayAudioRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new network.cow.environment.protocol.v1.PlayAudioRequest();
  }

  public static network.cow.environment.protocol.v1.PlayAudioRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PlayAudioRequest>
      PARSER = new com.google.protobuf.AbstractParser<PlayAudioRequest>() {
    @java.lang.Override
    public PlayAudioRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PlayAudioRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PlayAudioRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PlayAudioRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public network.cow.environment.protocol.v1.PlayAudioRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

