// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service_requests.proto

package network.cow.environment.protocol.v1;

public interface RegisterConsumerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cow.environment.v1.RegisterConsumerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string context_id = 1;</code>
   * @return The contextId.
   */
  java.lang.String getContextId();
  /**
   * <code>string context_id = 1;</code>
   * @return The bytes for contextId.
   */
  com.google.protobuf.ByteString
      getContextIdBytes();
}
