// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service_requests.proto

package network.cow.environment.protocol.v1;

public final class ServiceRequests {
  private ServiceRequests() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cow_environment_v1_RegisterConsumerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cow_environment_v1_RegisterConsumerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cow_environment_v1_UnregisterConsumerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cow_environment_v1_UnregisterConsumerRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026service_requests.proto\022\022cow.environmen" +
      "t.v1\"-\n\027RegisterConsumerRequest\022\022\n\nconte" +
      "xt_id\030\001 \001(\t\"0\n\031UnregisterConsumerRequest" +
      "\022\023\n\013consumer_id\030\001 \001(\tB\'\n#network.cow.env" +
      "ironment.protocol.v1P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_cow_environment_v1_RegisterConsumerRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cow_environment_v1_RegisterConsumerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cow_environment_v1_RegisterConsumerRequest_descriptor,
        new java.lang.String[] { "ContextId", });
    internal_static_cow_environment_v1_UnregisterConsumerRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cow_environment_v1_UnregisterConsumerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cow_environment_v1_UnregisterConsumerRequest_descriptor,
        new java.lang.String[] { "ConsumerId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
