// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: consumer_requests.proto

package network.cow.environment.protocol.v1;

public interface SetPositionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cow.environment.v1.SetPositionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string consumer_id = 1;</code>
   * @return The consumerId.
   */
  java.lang.String getConsumerId();
  /**
   * <code>string consumer_id = 1;</code>
   * @return The bytes for consumerId.
   */
  com.google.protobuf.ByteString
      getConsumerIdBytes();

  /**
   * <code>.cow.environment.v1.Vector position = 2;</code>
   * @return Whether the position field is set.
   */
  boolean hasPosition();
  /**
   * <code>.cow.environment.v1.Vector position = 2;</code>
   * @return The position.
   */
  network.cow.environment.protocol.v1.Vector getPosition();
  /**
   * <code>.cow.environment.v1.Vector position = 2;</code>
   */
  network.cow.environment.protocol.v1.VectorOrBuilder getPositionOrBuilder();

  /**
   * <code>.cow.environment.v1.Vector front = 3;</code>
   * @return Whether the front field is set.
   */
  boolean hasFront();
  /**
   * <code>.cow.environment.v1.Vector front = 3;</code>
   * @return The front.
   */
  network.cow.environment.protocol.v1.Vector getFront();
  /**
   * <code>.cow.environment.v1.Vector front = 3;</code>
   */
  network.cow.environment.protocol.v1.VectorOrBuilder getFrontOrBuilder();

  /**
   * <code>.cow.environment.v1.Vector up = 4;</code>
   * @return Whether the up field is set.
   */
  boolean hasUp();
  /**
   * <code>.cow.environment.v1.Vector up = 4;</code>
   * @return The up.
   */
  network.cow.environment.protocol.v1.Vector getUp();
  /**
   * <code>.cow.environment.v1.Vector up = 4;</code>
   */
  network.cow.environment.protocol.v1.VectorOrBuilder getUpOrBuilder();
}
