// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: consumer_requests.proto

package network.cow.environment.protocol.v1;

/**
 * Protobuf type {@code cow.environment.v1.SetPositionRequest}
 */
public final class SetPositionRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cow.environment.v1.SetPositionRequest)
    SetPositionRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SetPositionRequest.newBuilder() to construct.
  private SetPositionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SetPositionRequest() {
    consumerId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SetPositionRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SetPositionRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            consumerId_ = s;
            break;
          }
          case 18: {
            network.cow.environment.protocol.v1.Vector.Builder subBuilder = null;
            if (position_ != null) {
              subBuilder = position_.toBuilder();
            }
            position_ = input.readMessage(network.cow.environment.protocol.v1.Vector.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(position_);
              position_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            network.cow.environment.protocol.v1.Vector.Builder subBuilder = null;
            if (front_ != null) {
              subBuilder = front_.toBuilder();
            }
            front_ = input.readMessage(network.cow.environment.protocol.v1.Vector.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(front_);
              front_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            network.cow.environment.protocol.v1.Vector.Builder subBuilder = null;
            if (up_ != null) {
              subBuilder = up_.toBuilder();
            }
            up_ = input.readMessage(network.cow.environment.protocol.v1.Vector.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(up_);
              up_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return network.cow.environment.protocol.v1.ConsumerRequests.internal_static_cow_environment_v1_SetPositionRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return network.cow.environment.protocol.v1.ConsumerRequests.internal_static_cow_environment_v1_SetPositionRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            network.cow.environment.protocol.v1.SetPositionRequest.class, network.cow.environment.protocol.v1.SetPositionRequest.Builder.class);
  }

  public static final int CONSUMER_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object consumerId_;
  /**
   * <code>string consumer_id = 1;</code>
   * @return The consumerId.
   */
  @java.lang.Override
  public java.lang.String getConsumerId() {
    java.lang.Object ref = consumerId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      consumerId_ = s;
      return s;
    }
  }
  /**
   * <code>string consumer_id = 1;</code>
   * @return The bytes for consumerId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getConsumerIdBytes() {
    java.lang.Object ref = consumerId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      consumerId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int POSITION_FIELD_NUMBER = 2;
  private network.cow.environment.protocol.v1.Vector position_;
  /**
   * <code>.cow.environment.v1.Vector position = 2;</code>
   * @return Whether the position field is set.
   */
  @java.lang.Override
  public boolean hasPosition() {
    return position_ != null;
  }
  /**
   * <code>.cow.environment.v1.Vector position = 2;</code>
   * @return The position.
   */
  @java.lang.Override
  public network.cow.environment.protocol.v1.Vector getPosition() {
    return position_ == null ? network.cow.environment.protocol.v1.Vector.getDefaultInstance() : position_;
  }
  /**
   * <code>.cow.environment.v1.Vector position = 2;</code>
   */
  @java.lang.Override
  public network.cow.environment.protocol.v1.VectorOrBuilder getPositionOrBuilder() {
    return getPosition();
  }

  public static final int FRONT_FIELD_NUMBER = 3;
  private network.cow.environment.protocol.v1.Vector front_;
  /**
   * <code>.cow.environment.v1.Vector front = 3;</code>
   * @return Whether the front field is set.
   */
  @java.lang.Override
  public boolean hasFront() {
    return front_ != null;
  }
  /**
   * <code>.cow.environment.v1.Vector front = 3;</code>
   * @return The front.
   */
  @java.lang.Override
  public network.cow.environment.protocol.v1.Vector getFront() {
    return front_ == null ? network.cow.environment.protocol.v1.Vector.getDefaultInstance() : front_;
  }
  /**
   * <code>.cow.environment.v1.Vector front = 3;</code>
   */
  @java.lang.Override
  public network.cow.environment.protocol.v1.VectorOrBuilder getFrontOrBuilder() {
    return getFront();
  }

  public static final int UP_FIELD_NUMBER = 4;
  private network.cow.environment.protocol.v1.Vector up_;
  /**
   * <code>.cow.environment.v1.Vector up = 4;</code>
   * @return Whether the up field is set.
   */
  @java.lang.Override
  public boolean hasUp() {
    return up_ != null;
  }
  /**
   * <code>.cow.environment.v1.Vector up = 4;</code>
   * @return The up.
   */
  @java.lang.Override
  public network.cow.environment.protocol.v1.Vector getUp() {
    return up_ == null ? network.cow.environment.protocol.v1.Vector.getDefaultInstance() : up_;
  }
  /**
   * <code>.cow.environment.v1.Vector up = 4;</code>
   */
  @java.lang.Override
  public network.cow.environment.protocol.v1.VectorOrBuilder getUpOrBuilder() {
    return getUp();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getConsumerIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, consumerId_);
    }
    if (position_ != null) {
      output.writeMessage(2, getPosition());
    }
    if (front_ != null) {
      output.writeMessage(3, getFront());
    }
    if (up_ != null) {
      output.writeMessage(4, getUp());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getConsumerIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, consumerId_);
    }
    if (position_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPosition());
    }
    if (front_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getFront());
    }
    if (up_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getUp());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof network.cow.environment.protocol.v1.SetPositionRequest)) {
      return super.equals(obj);
    }
    network.cow.environment.protocol.v1.SetPositionRequest other = (network.cow.environment.protocol.v1.SetPositionRequest) obj;

    if (!getConsumerId()
        .equals(other.getConsumerId())) return false;
    if (hasPosition() != other.hasPosition()) return false;
    if (hasPosition()) {
      if (!getPosition()
          .equals(other.getPosition())) return false;
    }
    if (hasFront() != other.hasFront()) return false;
    if (hasFront()) {
      if (!getFront()
          .equals(other.getFront())) return false;
    }
    if (hasUp() != other.hasUp()) return false;
    if (hasUp()) {
      if (!getUp()
          .equals(other.getUp())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CONSUMER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getConsumerId().hashCode();
    if (hasPosition()) {
      hash = (37 * hash) + POSITION_FIELD_NUMBER;
      hash = (53 * hash) + getPosition().hashCode();
    }
    if (hasFront()) {
      hash = (37 * hash) + FRONT_FIELD_NUMBER;
      hash = (53 * hash) + getFront().hashCode();
    }
    if (hasUp()) {
      hash = (37 * hash) + UP_FIELD_NUMBER;
      hash = (53 * hash) + getUp().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static network.cow.environment.protocol.v1.SetPositionRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static network.cow.environment.protocol.v1.SetPositionRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static network.cow.environment.protocol.v1.SetPositionRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static network.cow.environment.protocol.v1.SetPositionRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static network.cow.environment.protocol.v1.SetPositionRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static network.cow.environment.protocol.v1.SetPositionRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static network.cow.environment.protocol.v1.SetPositionRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static network.cow.environment.protocol.v1.SetPositionRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static network.cow.environment.protocol.v1.SetPositionRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static network.cow.environment.protocol.v1.SetPositionRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static network.cow.environment.protocol.v1.SetPositionRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static network.cow.environment.protocol.v1.SetPositionRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(network.cow.environment.protocol.v1.SetPositionRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code cow.environment.v1.SetPositionRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cow.environment.v1.SetPositionRequest)
      network.cow.environment.protocol.v1.SetPositionRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return network.cow.environment.protocol.v1.ConsumerRequests.internal_static_cow_environment_v1_SetPositionRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return network.cow.environment.protocol.v1.ConsumerRequests.internal_static_cow_environment_v1_SetPositionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              network.cow.environment.protocol.v1.SetPositionRequest.class, network.cow.environment.protocol.v1.SetPositionRequest.Builder.class);
    }

    // Construct using network.cow.environment.protocol.v1.SetPositionRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      consumerId_ = "";

      if (positionBuilder_ == null) {
        position_ = null;
      } else {
        position_ = null;
        positionBuilder_ = null;
      }
      if (frontBuilder_ == null) {
        front_ = null;
      } else {
        front_ = null;
        frontBuilder_ = null;
      }
      if (upBuilder_ == null) {
        up_ = null;
      } else {
        up_ = null;
        upBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return network.cow.environment.protocol.v1.ConsumerRequests.internal_static_cow_environment_v1_SetPositionRequest_descriptor;
    }

    @java.lang.Override
    public network.cow.environment.protocol.v1.SetPositionRequest getDefaultInstanceForType() {
      return network.cow.environment.protocol.v1.SetPositionRequest.getDefaultInstance();
    }

    @java.lang.Override
    public network.cow.environment.protocol.v1.SetPositionRequest build() {
      network.cow.environment.protocol.v1.SetPositionRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public network.cow.environment.protocol.v1.SetPositionRequest buildPartial() {
      network.cow.environment.protocol.v1.SetPositionRequest result = new network.cow.environment.protocol.v1.SetPositionRequest(this);
      result.consumerId_ = consumerId_;
      if (positionBuilder_ == null) {
        result.position_ = position_;
      } else {
        result.position_ = positionBuilder_.build();
      }
      if (frontBuilder_ == null) {
        result.front_ = front_;
      } else {
        result.front_ = frontBuilder_.build();
      }
      if (upBuilder_ == null) {
        result.up_ = up_;
      } else {
        result.up_ = upBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof network.cow.environment.protocol.v1.SetPositionRequest) {
        return mergeFrom((network.cow.environment.protocol.v1.SetPositionRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(network.cow.environment.protocol.v1.SetPositionRequest other) {
      if (other == network.cow.environment.protocol.v1.SetPositionRequest.getDefaultInstance()) return this;
      if (!other.getConsumerId().isEmpty()) {
        consumerId_ = other.consumerId_;
        onChanged();
      }
      if (other.hasPosition()) {
        mergePosition(other.getPosition());
      }
      if (other.hasFront()) {
        mergeFront(other.getFront());
      }
      if (other.hasUp()) {
        mergeUp(other.getUp());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      network.cow.environment.protocol.v1.SetPositionRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (network.cow.environment.protocol.v1.SetPositionRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object consumerId_ = "";
    /**
     * <code>string consumer_id = 1;</code>
     * @return The consumerId.
     */
    public java.lang.String getConsumerId() {
      java.lang.Object ref = consumerId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        consumerId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string consumer_id = 1;</code>
     * @return The bytes for consumerId.
     */
    public com.google.protobuf.ByteString
        getConsumerIdBytes() {
      java.lang.Object ref = consumerId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        consumerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string consumer_id = 1;</code>
     * @param value The consumerId to set.
     * @return This builder for chaining.
     */
    public Builder setConsumerId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      consumerId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string consumer_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearConsumerId() {
      
      consumerId_ = getDefaultInstance().getConsumerId();
      onChanged();
      return this;
    }
    /**
     * <code>string consumer_id = 1;</code>
     * @param value The bytes for consumerId to set.
     * @return This builder for chaining.
     */
    public Builder setConsumerIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      consumerId_ = value;
      onChanged();
      return this;
    }

    private network.cow.environment.protocol.v1.Vector position_;
    private com.google.protobuf.SingleFieldBuilderV3<
        network.cow.environment.protocol.v1.Vector, network.cow.environment.protocol.v1.Vector.Builder, network.cow.environment.protocol.v1.VectorOrBuilder> positionBuilder_;
    /**
     * <code>.cow.environment.v1.Vector position = 2;</code>
     * @return Whether the position field is set.
     */
    public boolean hasPosition() {
      return positionBuilder_ != null || position_ != null;
    }
    /**
     * <code>.cow.environment.v1.Vector position = 2;</code>
     * @return The position.
     */
    public network.cow.environment.protocol.v1.Vector getPosition() {
      if (positionBuilder_ == null) {
        return position_ == null ? network.cow.environment.protocol.v1.Vector.getDefaultInstance() : position_;
      } else {
        return positionBuilder_.getMessage();
      }
    }
    /**
     * <code>.cow.environment.v1.Vector position = 2;</code>
     */
    public Builder setPosition(network.cow.environment.protocol.v1.Vector value) {
      if (positionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        position_ = value;
        onChanged();
      } else {
        positionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.cow.environment.v1.Vector position = 2;</code>
     */
    public Builder setPosition(
        network.cow.environment.protocol.v1.Vector.Builder builderForValue) {
      if (positionBuilder_ == null) {
        position_ = builderForValue.build();
        onChanged();
      } else {
        positionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.cow.environment.v1.Vector position = 2;</code>
     */
    public Builder mergePosition(network.cow.environment.protocol.v1.Vector value) {
      if (positionBuilder_ == null) {
        if (position_ != null) {
          position_ =
            network.cow.environment.protocol.v1.Vector.newBuilder(position_).mergeFrom(value).buildPartial();
        } else {
          position_ = value;
        }
        onChanged();
      } else {
        positionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.cow.environment.v1.Vector position = 2;</code>
     */
    public Builder clearPosition() {
      if (positionBuilder_ == null) {
        position_ = null;
        onChanged();
      } else {
        position_ = null;
        positionBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.cow.environment.v1.Vector position = 2;</code>
     */
    public network.cow.environment.protocol.v1.Vector.Builder getPositionBuilder() {
      
      onChanged();
      return getPositionFieldBuilder().getBuilder();
    }
    /**
     * <code>.cow.environment.v1.Vector position = 2;</code>
     */
    public network.cow.environment.protocol.v1.VectorOrBuilder getPositionOrBuilder() {
      if (positionBuilder_ != null) {
        return positionBuilder_.getMessageOrBuilder();
      } else {
        return position_ == null ?
            network.cow.environment.protocol.v1.Vector.getDefaultInstance() : position_;
      }
    }
    /**
     * <code>.cow.environment.v1.Vector position = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        network.cow.environment.protocol.v1.Vector, network.cow.environment.protocol.v1.Vector.Builder, network.cow.environment.protocol.v1.VectorOrBuilder> 
        getPositionFieldBuilder() {
      if (positionBuilder_ == null) {
        positionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            network.cow.environment.protocol.v1.Vector, network.cow.environment.protocol.v1.Vector.Builder, network.cow.environment.protocol.v1.VectorOrBuilder>(
                getPosition(),
                getParentForChildren(),
                isClean());
        position_ = null;
      }
      return positionBuilder_;
    }

    private network.cow.environment.protocol.v1.Vector front_;
    private com.google.protobuf.SingleFieldBuilderV3<
        network.cow.environment.protocol.v1.Vector, network.cow.environment.protocol.v1.Vector.Builder, network.cow.environment.protocol.v1.VectorOrBuilder> frontBuilder_;
    /**
     * <code>.cow.environment.v1.Vector front = 3;</code>
     * @return Whether the front field is set.
     */
    public boolean hasFront() {
      return frontBuilder_ != null || front_ != null;
    }
    /**
     * <code>.cow.environment.v1.Vector front = 3;</code>
     * @return The front.
     */
    public network.cow.environment.protocol.v1.Vector getFront() {
      if (frontBuilder_ == null) {
        return front_ == null ? network.cow.environment.protocol.v1.Vector.getDefaultInstance() : front_;
      } else {
        return frontBuilder_.getMessage();
      }
    }
    /**
     * <code>.cow.environment.v1.Vector front = 3;</code>
     */
    public Builder setFront(network.cow.environment.protocol.v1.Vector value) {
      if (frontBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        front_ = value;
        onChanged();
      } else {
        frontBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.cow.environment.v1.Vector front = 3;</code>
     */
    public Builder setFront(
        network.cow.environment.protocol.v1.Vector.Builder builderForValue) {
      if (frontBuilder_ == null) {
        front_ = builderForValue.build();
        onChanged();
      } else {
        frontBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.cow.environment.v1.Vector front = 3;</code>
     */
    public Builder mergeFront(network.cow.environment.protocol.v1.Vector value) {
      if (frontBuilder_ == null) {
        if (front_ != null) {
          front_ =
            network.cow.environment.protocol.v1.Vector.newBuilder(front_).mergeFrom(value).buildPartial();
        } else {
          front_ = value;
        }
        onChanged();
      } else {
        frontBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.cow.environment.v1.Vector front = 3;</code>
     */
    public Builder clearFront() {
      if (frontBuilder_ == null) {
        front_ = null;
        onChanged();
      } else {
        front_ = null;
        frontBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.cow.environment.v1.Vector front = 3;</code>
     */
    public network.cow.environment.protocol.v1.Vector.Builder getFrontBuilder() {
      
      onChanged();
      return getFrontFieldBuilder().getBuilder();
    }
    /**
     * <code>.cow.environment.v1.Vector front = 3;</code>
     */
    public network.cow.environment.protocol.v1.VectorOrBuilder getFrontOrBuilder() {
      if (frontBuilder_ != null) {
        return frontBuilder_.getMessageOrBuilder();
      } else {
        return front_ == null ?
            network.cow.environment.protocol.v1.Vector.getDefaultInstance() : front_;
      }
    }
    /**
     * <code>.cow.environment.v1.Vector front = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        network.cow.environment.protocol.v1.Vector, network.cow.environment.protocol.v1.Vector.Builder, network.cow.environment.protocol.v1.VectorOrBuilder> 
        getFrontFieldBuilder() {
      if (frontBuilder_ == null) {
        frontBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            network.cow.environment.protocol.v1.Vector, network.cow.environment.protocol.v1.Vector.Builder, network.cow.environment.protocol.v1.VectorOrBuilder>(
                getFront(),
                getParentForChildren(),
                isClean());
        front_ = null;
      }
      return frontBuilder_;
    }

    private network.cow.environment.protocol.v1.Vector up_;
    private com.google.protobuf.SingleFieldBuilderV3<
        network.cow.environment.protocol.v1.Vector, network.cow.environment.protocol.v1.Vector.Builder, network.cow.environment.protocol.v1.VectorOrBuilder> upBuilder_;
    /**
     * <code>.cow.environment.v1.Vector up = 4;</code>
     * @return Whether the up field is set.
     */
    public boolean hasUp() {
      return upBuilder_ != null || up_ != null;
    }
    /**
     * <code>.cow.environment.v1.Vector up = 4;</code>
     * @return The up.
     */
    public network.cow.environment.protocol.v1.Vector getUp() {
      if (upBuilder_ == null) {
        return up_ == null ? network.cow.environment.protocol.v1.Vector.getDefaultInstance() : up_;
      } else {
        return upBuilder_.getMessage();
      }
    }
    /**
     * <code>.cow.environment.v1.Vector up = 4;</code>
     */
    public Builder setUp(network.cow.environment.protocol.v1.Vector value) {
      if (upBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        up_ = value;
        onChanged();
      } else {
        upBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.cow.environment.v1.Vector up = 4;</code>
     */
    public Builder setUp(
        network.cow.environment.protocol.v1.Vector.Builder builderForValue) {
      if (upBuilder_ == null) {
        up_ = builderForValue.build();
        onChanged();
      } else {
        upBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.cow.environment.v1.Vector up = 4;</code>
     */
    public Builder mergeUp(network.cow.environment.protocol.v1.Vector value) {
      if (upBuilder_ == null) {
        if (up_ != null) {
          up_ =
            network.cow.environment.protocol.v1.Vector.newBuilder(up_).mergeFrom(value).buildPartial();
        } else {
          up_ = value;
        }
        onChanged();
      } else {
        upBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.cow.environment.v1.Vector up = 4;</code>
     */
    public Builder clearUp() {
      if (upBuilder_ == null) {
        up_ = null;
        onChanged();
      } else {
        up_ = null;
        upBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.cow.environment.v1.Vector up = 4;</code>
     */
    public network.cow.environment.protocol.v1.Vector.Builder getUpBuilder() {
      
      onChanged();
      return getUpFieldBuilder().getBuilder();
    }
    /**
     * <code>.cow.environment.v1.Vector up = 4;</code>
     */
    public network.cow.environment.protocol.v1.VectorOrBuilder getUpOrBuilder() {
      if (upBuilder_ != null) {
        return upBuilder_.getMessageOrBuilder();
      } else {
        return up_ == null ?
            network.cow.environment.protocol.v1.Vector.getDefaultInstance() : up_;
      }
    }
    /**
     * <code>.cow.environment.v1.Vector up = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        network.cow.environment.protocol.v1.Vector, network.cow.environment.protocol.v1.Vector.Builder, network.cow.environment.protocol.v1.VectorOrBuilder> 
        getUpFieldBuilder() {
      if (upBuilder_ == null) {
        upBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            network.cow.environment.protocol.v1.Vector, network.cow.environment.protocol.v1.Vector.Builder, network.cow.environment.protocol.v1.VectorOrBuilder>(
                getUp(),
                getParentForChildren(),
                isClean());
        up_ = null;
      }
      return upBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:cow.environment.v1.SetPositionRequest)
  }

  // @@protoc_insertion_point(class_scope:cow.environment.v1.SetPositionRequest)
  private static final network.cow.environment.protocol.v1.SetPositionRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new network.cow.environment.protocol.v1.SetPositionRequest();
  }

  public static network.cow.environment.protocol.v1.SetPositionRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SetPositionRequest>
      PARSER = new com.google.protobuf.AbstractParser<SetPositionRequest>() {
    @java.lang.Override
    public SetPositionRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SetPositionRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SetPositionRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SetPositionRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public network.cow.environment.protocol.v1.SetPositionRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

