// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: consumer_requests.proto

package network.cow.environment.protocol.v1;

public interface SpriteOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cow.environment.v1.Sprite)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 from = 1;</code>
   * @return The from.
   */
  int getFrom();

  /**
   * <code>int32 to = 2;</code>
   * @return The to.
   */
  int getTo();
}
