// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: consumer_requests.proto

package network.cow.environment.protocol.v1;

/**
 * Protobuf type {@code cow.environment.v1.UpdateAudioRequest}
 */
public final class UpdateAudioRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cow.environment.v1.UpdateAudioRequest)
    UpdateAudioRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UpdateAudioRequest.newBuilder() to construct.
  private UpdateAudioRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UpdateAudioRequest() {
    consumerId_ = "";
    id_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UpdateAudioRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UpdateAudioRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            consumerId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 25: {

            volume_ = input.readDouble();
            break;
          }
          case 33: {

            rate_ = input.readDouble();
            break;
          }
          case 40: {

            loop_ = input.readBool();
            break;
          }
          case 48: {

            loopFadeDuration_ = input.readInt32();
            break;
          }
          case 58: {
            network.cow.environment.protocol.v1.Vector.Builder subBuilder = null;
            if (position_ != null) {
              subBuilder = position_.toBuilder();
            }
            position_ = input.readMessage(network.cow.environment.protocol.v1.Vector.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(position_);
              position_ = subBuilder.buildPartial();
            }

            break;
          }
          case 66: {
            network.cow.environment.protocol.v1.PannerAttributes.Builder subBuilder = null;
            if (pannerAttributes_ != null) {
              subBuilder = pannerAttributes_.toBuilder();
            }
            pannerAttributes_ = input.readMessage(network.cow.environment.protocol.v1.PannerAttributes.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(pannerAttributes_);
              pannerAttributes_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return network.cow.environment.protocol.v1.ConsumerRequests.internal_static_cow_environment_v1_UpdateAudioRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return network.cow.environment.protocol.v1.ConsumerRequests.internal_static_cow_environment_v1_UpdateAudioRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            network.cow.environment.protocol.v1.UpdateAudioRequest.class, network.cow.environment.protocol.v1.UpdateAudioRequest.Builder.class);
  }

  public static final int CONSUMER_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object consumerId_;
  /**
   * <code>string consumer_id = 1;</code>
   * @return The consumerId.
   */
  @java.lang.Override
  public java.lang.String getConsumerId() {
    java.lang.Object ref = consumerId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      consumerId_ = s;
      return s;
    }
  }
  /**
   * <code>string consumer_id = 1;</code>
   * @return The bytes for consumerId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getConsumerIdBytes() {
    java.lang.Object ref = consumerId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      consumerId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 2;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 2;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VOLUME_FIELD_NUMBER = 3;
  private double volume_;
  /**
   * <code>double volume = 3;</code>
   * @return The volume.
   */
  @java.lang.Override
  public double getVolume() {
    return volume_;
  }

  public static final int RATE_FIELD_NUMBER = 4;
  private double rate_;
  /**
   * <code>double rate = 4;</code>
   * @return The rate.
   */
  @java.lang.Override
  public double getRate() {
    return rate_;
  }

  public static final int LOOP_FIELD_NUMBER = 5;
  private boolean loop_;
  /**
   * <code>bool loop = 5;</code>
   * @return The loop.
   */
  @java.lang.Override
  public boolean getLoop() {
    return loop_;
  }

  public static final int LOOPFADEDURATION_FIELD_NUMBER = 6;
  private int loopFadeDuration_;
  /**
   * <code>int32 loopFadeDuration = 6;</code>
   * @return The loopFadeDuration.
   */
  @java.lang.Override
  public int getLoopFadeDuration() {
    return loopFadeDuration_;
  }

  public static final int POSITION_FIELD_NUMBER = 7;
  private network.cow.environment.protocol.v1.Vector position_;
  /**
   * <code>.cow.environment.v1.Vector position = 7;</code>
   * @return Whether the position field is set.
   */
  @java.lang.Override
  public boolean hasPosition() {
    return position_ != null;
  }
  /**
   * <code>.cow.environment.v1.Vector position = 7;</code>
   * @return The position.
   */
  @java.lang.Override
  public network.cow.environment.protocol.v1.Vector getPosition() {
    return position_ == null ? network.cow.environment.protocol.v1.Vector.getDefaultInstance() : position_;
  }
  /**
   * <code>.cow.environment.v1.Vector position = 7;</code>
   */
  @java.lang.Override
  public network.cow.environment.protocol.v1.VectorOrBuilder getPositionOrBuilder() {
    return getPosition();
  }

  public static final int PANNERATTRIBUTES_FIELD_NUMBER = 8;
  private network.cow.environment.protocol.v1.PannerAttributes pannerAttributes_;
  /**
   * <code>.cow.environment.v1.PannerAttributes pannerAttributes = 8;</code>
   * @return Whether the pannerAttributes field is set.
   */
  @java.lang.Override
  public boolean hasPannerAttributes() {
    return pannerAttributes_ != null;
  }
  /**
   * <code>.cow.environment.v1.PannerAttributes pannerAttributes = 8;</code>
   * @return The pannerAttributes.
   */
  @java.lang.Override
  public network.cow.environment.protocol.v1.PannerAttributes getPannerAttributes() {
    return pannerAttributes_ == null ? network.cow.environment.protocol.v1.PannerAttributes.getDefaultInstance() : pannerAttributes_;
  }
  /**
   * <code>.cow.environment.v1.PannerAttributes pannerAttributes = 8;</code>
   */
  @java.lang.Override
  public network.cow.environment.protocol.v1.PannerAttributesOrBuilder getPannerAttributesOrBuilder() {
    return getPannerAttributes();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getConsumerIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, consumerId_);
    }
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, id_);
    }
    if (volume_ != 0D) {
      output.writeDouble(3, volume_);
    }
    if (rate_ != 0D) {
      output.writeDouble(4, rate_);
    }
    if (loop_ != false) {
      output.writeBool(5, loop_);
    }
    if (loopFadeDuration_ != 0) {
      output.writeInt32(6, loopFadeDuration_);
    }
    if (position_ != null) {
      output.writeMessage(7, getPosition());
    }
    if (pannerAttributes_ != null) {
      output.writeMessage(8, getPannerAttributes());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getConsumerIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, consumerId_);
    }
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, id_);
    }
    if (volume_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, volume_);
    }
    if (rate_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, rate_);
    }
    if (loop_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, loop_);
    }
    if (loopFadeDuration_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, loopFadeDuration_);
    }
    if (position_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getPosition());
    }
    if (pannerAttributes_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getPannerAttributes());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof network.cow.environment.protocol.v1.UpdateAudioRequest)) {
      return super.equals(obj);
    }
    network.cow.environment.protocol.v1.UpdateAudioRequest other = (network.cow.environment.protocol.v1.UpdateAudioRequest) obj;

    if (!getConsumerId()
        .equals(other.getConsumerId())) return false;
    if (!getId()
        .equals(other.getId())) return false;
    if (java.lang.Double.doubleToLongBits(getVolume())
        != java.lang.Double.doubleToLongBits(
            other.getVolume())) return false;
    if (java.lang.Double.doubleToLongBits(getRate())
        != java.lang.Double.doubleToLongBits(
            other.getRate())) return false;
    if (getLoop()
        != other.getLoop()) return false;
    if (getLoopFadeDuration()
        != other.getLoopFadeDuration()) return false;
    if (hasPosition() != other.hasPosition()) return false;
    if (hasPosition()) {
      if (!getPosition()
          .equals(other.getPosition())) return false;
    }
    if (hasPannerAttributes() != other.hasPannerAttributes()) return false;
    if (hasPannerAttributes()) {
      if (!getPannerAttributes()
          .equals(other.getPannerAttributes())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CONSUMER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getConsumerId().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + VOLUME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getVolume()));
    hash = (37 * hash) + RATE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getRate()));
    hash = (37 * hash) + LOOP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getLoop());
    hash = (37 * hash) + LOOPFADEDURATION_FIELD_NUMBER;
    hash = (53 * hash) + getLoopFadeDuration();
    if (hasPosition()) {
      hash = (37 * hash) + POSITION_FIELD_NUMBER;
      hash = (53 * hash) + getPosition().hashCode();
    }
    if (hasPannerAttributes()) {
      hash = (37 * hash) + PANNERATTRIBUTES_FIELD_NUMBER;
      hash = (53 * hash) + getPannerAttributes().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static network.cow.environment.protocol.v1.UpdateAudioRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static network.cow.environment.protocol.v1.UpdateAudioRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static network.cow.environment.protocol.v1.UpdateAudioRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static network.cow.environment.protocol.v1.UpdateAudioRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static network.cow.environment.protocol.v1.UpdateAudioRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static network.cow.environment.protocol.v1.UpdateAudioRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static network.cow.environment.protocol.v1.UpdateAudioRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static network.cow.environment.protocol.v1.UpdateAudioRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static network.cow.environment.protocol.v1.UpdateAudioRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static network.cow.environment.protocol.v1.UpdateAudioRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static network.cow.environment.protocol.v1.UpdateAudioRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static network.cow.environment.protocol.v1.UpdateAudioRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(network.cow.environment.protocol.v1.UpdateAudioRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code cow.environment.v1.UpdateAudioRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cow.environment.v1.UpdateAudioRequest)
      network.cow.environment.protocol.v1.UpdateAudioRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return network.cow.environment.protocol.v1.ConsumerRequests.internal_static_cow_environment_v1_UpdateAudioRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return network.cow.environment.protocol.v1.ConsumerRequests.internal_static_cow_environment_v1_UpdateAudioRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              network.cow.environment.protocol.v1.UpdateAudioRequest.class, network.cow.environment.protocol.v1.UpdateAudioRequest.Builder.class);
    }

    // Construct using network.cow.environment.protocol.v1.UpdateAudioRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      consumerId_ = "";

      id_ = "";

      volume_ = 0D;

      rate_ = 0D;

      loop_ = false;

      loopFadeDuration_ = 0;

      if (positionBuilder_ == null) {
        position_ = null;
      } else {
        position_ = null;
        positionBuilder_ = null;
      }
      if (pannerAttributesBuilder_ == null) {
        pannerAttributes_ = null;
      } else {
        pannerAttributes_ = null;
        pannerAttributesBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return network.cow.environment.protocol.v1.ConsumerRequests.internal_static_cow_environment_v1_UpdateAudioRequest_descriptor;
    }

    @java.lang.Override
    public network.cow.environment.protocol.v1.UpdateAudioRequest getDefaultInstanceForType() {
      return network.cow.environment.protocol.v1.UpdateAudioRequest.getDefaultInstance();
    }

    @java.lang.Override
    public network.cow.environment.protocol.v1.UpdateAudioRequest build() {
      network.cow.environment.protocol.v1.UpdateAudioRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public network.cow.environment.protocol.v1.UpdateAudioRequest buildPartial() {
      network.cow.environment.protocol.v1.UpdateAudioRequest result = new network.cow.environment.protocol.v1.UpdateAudioRequest(this);
      result.consumerId_ = consumerId_;
      result.id_ = id_;
      result.volume_ = volume_;
      result.rate_ = rate_;
      result.loop_ = loop_;
      result.loopFadeDuration_ = loopFadeDuration_;
      if (positionBuilder_ == null) {
        result.position_ = position_;
      } else {
        result.position_ = positionBuilder_.build();
      }
      if (pannerAttributesBuilder_ == null) {
        result.pannerAttributes_ = pannerAttributes_;
      } else {
        result.pannerAttributes_ = pannerAttributesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof network.cow.environment.protocol.v1.UpdateAudioRequest) {
        return mergeFrom((network.cow.environment.protocol.v1.UpdateAudioRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(network.cow.environment.protocol.v1.UpdateAudioRequest other) {
      if (other == network.cow.environment.protocol.v1.UpdateAudioRequest.getDefaultInstance()) return this;
      if (!other.getConsumerId().isEmpty()) {
        consumerId_ = other.consumerId_;
        onChanged();
      }
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (other.getVolume() != 0D) {
        setVolume(other.getVolume());
      }
      if (other.getRate() != 0D) {
        setRate(other.getRate());
      }
      if (other.getLoop() != false) {
        setLoop(other.getLoop());
      }
      if (other.getLoopFadeDuration() != 0) {
        setLoopFadeDuration(other.getLoopFadeDuration());
      }
      if (other.hasPosition()) {
        mergePosition(other.getPosition());
      }
      if (other.hasPannerAttributes()) {
        mergePannerAttributes(other.getPannerAttributes());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      network.cow.environment.protocol.v1.UpdateAudioRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (network.cow.environment.protocol.v1.UpdateAudioRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object consumerId_ = "";
    /**
     * <code>string consumer_id = 1;</code>
     * @return The consumerId.
     */
    public java.lang.String getConsumerId() {
      java.lang.Object ref = consumerId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        consumerId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string consumer_id = 1;</code>
     * @return The bytes for consumerId.
     */
    public com.google.protobuf.ByteString
        getConsumerIdBytes() {
      java.lang.Object ref = consumerId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        consumerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string consumer_id = 1;</code>
     * @param value The consumerId to set.
     * @return This builder for chaining.
     */
    public Builder setConsumerId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      consumerId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string consumer_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearConsumerId() {
      
      consumerId_ = getDefaultInstance().getConsumerId();
      onChanged();
      return this;
    }
    /**
     * <code>string consumer_id = 1;</code>
     * @param value The bytes for consumerId to set.
     * @return This builder for chaining.
     */
    public Builder setConsumerIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      consumerId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 2;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 2;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 2;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 2;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private double volume_ ;
    /**
     * <code>double volume = 3;</code>
     * @return The volume.
     */
    @java.lang.Override
    public double getVolume() {
      return volume_;
    }
    /**
     * <code>double volume = 3;</code>
     * @param value The volume to set.
     * @return This builder for chaining.
     */
    public Builder setVolume(double value) {
      
      volume_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double volume = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearVolume() {
      
      volume_ = 0D;
      onChanged();
      return this;
    }

    private double rate_ ;
    /**
     * <code>double rate = 4;</code>
     * @return The rate.
     */
    @java.lang.Override
    public double getRate() {
      return rate_;
    }
    /**
     * <code>double rate = 4;</code>
     * @param value The rate to set.
     * @return This builder for chaining.
     */
    public Builder setRate(double value) {
      
      rate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double rate = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearRate() {
      
      rate_ = 0D;
      onChanged();
      return this;
    }

    private boolean loop_ ;
    /**
     * <code>bool loop = 5;</code>
     * @return The loop.
     */
    @java.lang.Override
    public boolean getLoop() {
      return loop_;
    }
    /**
     * <code>bool loop = 5;</code>
     * @param value The loop to set.
     * @return This builder for chaining.
     */
    public Builder setLoop(boolean value) {
      
      loop_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool loop = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearLoop() {
      
      loop_ = false;
      onChanged();
      return this;
    }

    private int loopFadeDuration_ ;
    /**
     * <code>int32 loopFadeDuration = 6;</code>
     * @return The loopFadeDuration.
     */
    @java.lang.Override
    public int getLoopFadeDuration() {
      return loopFadeDuration_;
    }
    /**
     * <code>int32 loopFadeDuration = 6;</code>
     * @param value The loopFadeDuration to set.
     * @return This builder for chaining.
     */
    public Builder setLoopFadeDuration(int value) {
      
      loopFadeDuration_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 loopFadeDuration = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearLoopFadeDuration() {
      
      loopFadeDuration_ = 0;
      onChanged();
      return this;
    }

    private network.cow.environment.protocol.v1.Vector position_;
    private com.google.protobuf.SingleFieldBuilderV3<
        network.cow.environment.protocol.v1.Vector, network.cow.environment.protocol.v1.Vector.Builder, network.cow.environment.protocol.v1.VectorOrBuilder> positionBuilder_;
    /**
     * <code>.cow.environment.v1.Vector position = 7;</code>
     * @return Whether the position field is set.
     */
    public boolean hasPosition() {
      return positionBuilder_ != null || position_ != null;
    }
    /**
     * <code>.cow.environment.v1.Vector position = 7;</code>
     * @return The position.
     */
    public network.cow.environment.protocol.v1.Vector getPosition() {
      if (positionBuilder_ == null) {
        return position_ == null ? network.cow.environment.protocol.v1.Vector.getDefaultInstance() : position_;
      } else {
        return positionBuilder_.getMessage();
      }
    }
    /**
     * <code>.cow.environment.v1.Vector position = 7;</code>
     */
    public Builder setPosition(network.cow.environment.protocol.v1.Vector value) {
      if (positionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        position_ = value;
        onChanged();
      } else {
        positionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.cow.environment.v1.Vector position = 7;</code>
     */
    public Builder setPosition(
        network.cow.environment.protocol.v1.Vector.Builder builderForValue) {
      if (positionBuilder_ == null) {
        position_ = builderForValue.build();
        onChanged();
      } else {
        positionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.cow.environment.v1.Vector position = 7;</code>
     */
    public Builder mergePosition(network.cow.environment.protocol.v1.Vector value) {
      if (positionBuilder_ == null) {
        if (position_ != null) {
          position_ =
            network.cow.environment.protocol.v1.Vector.newBuilder(position_).mergeFrom(value).buildPartial();
        } else {
          position_ = value;
        }
        onChanged();
      } else {
        positionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.cow.environment.v1.Vector position = 7;</code>
     */
    public Builder clearPosition() {
      if (positionBuilder_ == null) {
        position_ = null;
        onChanged();
      } else {
        position_ = null;
        positionBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.cow.environment.v1.Vector position = 7;</code>
     */
    public network.cow.environment.protocol.v1.Vector.Builder getPositionBuilder() {
      
      onChanged();
      return getPositionFieldBuilder().getBuilder();
    }
    /**
     * <code>.cow.environment.v1.Vector position = 7;</code>
     */
    public network.cow.environment.protocol.v1.VectorOrBuilder getPositionOrBuilder() {
      if (positionBuilder_ != null) {
        return positionBuilder_.getMessageOrBuilder();
      } else {
        return position_ == null ?
            network.cow.environment.protocol.v1.Vector.getDefaultInstance() : position_;
      }
    }
    /**
     * <code>.cow.environment.v1.Vector position = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        network.cow.environment.protocol.v1.Vector, network.cow.environment.protocol.v1.Vector.Builder, network.cow.environment.protocol.v1.VectorOrBuilder> 
        getPositionFieldBuilder() {
      if (positionBuilder_ == null) {
        positionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            network.cow.environment.protocol.v1.Vector, network.cow.environment.protocol.v1.Vector.Builder, network.cow.environment.protocol.v1.VectorOrBuilder>(
                getPosition(),
                getParentForChildren(),
                isClean());
        position_ = null;
      }
      return positionBuilder_;
    }

    private network.cow.environment.protocol.v1.PannerAttributes pannerAttributes_;
    private com.google.protobuf.SingleFieldBuilderV3<
        network.cow.environment.protocol.v1.PannerAttributes, network.cow.environment.protocol.v1.PannerAttributes.Builder, network.cow.environment.protocol.v1.PannerAttributesOrBuilder> pannerAttributesBuilder_;
    /**
     * <code>.cow.environment.v1.PannerAttributes pannerAttributes = 8;</code>
     * @return Whether the pannerAttributes field is set.
     */
    public boolean hasPannerAttributes() {
      return pannerAttributesBuilder_ != null || pannerAttributes_ != null;
    }
    /**
     * <code>.cow.environment.v1.PannerAttributes pannerAttributes = 8;</code>
     * @return The pannerAttributes.
     */
    public network.cow.environment.protocol.v1.PannerAttributes getPannerAttributes() {
      if (pannerAttributesBuilder_ == null) {
        return pannerAttributes_ == null ? network.cow.environment.protocol.v1.PannerAttributes.getDefaultInstance() : pannerAttributes_;
      } else {
        return pannerAttributesBuilder_.getMessage();
      }
    }
    /**
     * <code>.cow.environment.v1.PannerAttributes pannerAttributes = 8;</code>
     */
    public Builder setPannerAttributes(network.cow.environment.protocol.v1.PannerAttributes value) {
      if (pannerAttributesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pannerAttributes_ = value;
        onChanged();
      } else {
        pannerAttributesBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.cow.environment.v1.PannerAttributes pannerAttributes = 8;</code>
     */
    public Builder setPannerAttributes(
        network.cow.environment.protocol.v1.PannerAttributes.Builder builderForValue) {
      if (pannerAttributesBuilder_ == null) {
        pannerAttributes_ = builderForValue.build();
        onChanged();
      } else {
        pannerAttributesBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.cow.environment.v1.PannerAttributes pannerAttributes = 8;</code>
     */
    public Builder mergePannerAttributes(network.cow.environment.protocol.v1.PannerAttributes value) {
      if (pannerAttributesBuilder_ == null) {
        if (pannerAttributes_ != null) {
          pannerAttributes_ =
            network.cow.environment.protocol.v1.PannerAttributes.newBuilder(pannerAttributes_).mergeFrom(value).buildPartial();
        } else {
          pannerAttributes_ = value;
        }
        onChanged();
      } else {
        pannerAttributesBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.cow.environment.v1.PannerAttributes pannerAttributes = 8;</code>
     */
    public Builder clearPannerAttributes() {
      if (pannerAttributesBuilder_ == null) {
        pannerAttributes_ = null;
        onChanged();
      } else {
        pannerAttributes_ = null;
        pannerAttributesBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.cow.environment.v1.PannerAttributes pannerAttributes = 8;</code>
     */
    public network.cow.environment.protocol.v1.PannerAttributes.Builder getPannerAttributesBuilder() {
      
      onChanged();
      return getPannerAttributesFieldBuilder().getBuilder();
    }
    /**
     * <code>.cow.environment.v1.PannerAttributes pannerAttributes = 8;</code>
     */
    public network.cow.environment.protocol.v1.PannerAttributesOrBuilder getPannerAttributesOrBuilder() {
      if (pannerAttributesBuilder_ != null) {
        return pannerAttributesBuilder_.getMessageOrBuilder();
      } else {
        return pannerAttributes_ == null ?
            network.cow.environment.protocol.v1.PannerAttributes.getDefaultInstance() : pannerAttributes_;
      }
    }
    /**
     * <code>.cow.environment.v1.PannerAttributes pannerAttributes = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        network.cow.environment.protocol.v1.PannerAttributes, network.cow.environment.protocol.v1.PannerAttributes.Builder, network.cow.environment.protocol.v1.PannerAttributesOrBuilder> 
        getPannerAttributesFieldBuilder() {
      if (pannerAttributesBuilder_ == null) {
        pannerAttributesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            network.cow.environment.protocol.v1.PannerAttributes, network.cow.environment.protocol.v1.PannerAttributes.Builder, network.cow.environment.protocol.v1.PannerAttributesOrBuilder>(
                getPannerAttributes(),
                getParentForChildren(),
                isClean());
        pannerAttributes_ = null;
      }
      return pannerAttributesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:cow.environment.v1.UpdateAudioRequest)
  }

  // @@protoc_insertion_point(class_scope:cow.environment.v1.UpdateAudioRequest)
  private static final network.cow.environment.protocol.v1.UpdateAudioRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new network.cow.environment.protocol.v1.UpdateAudioRequest();
  }

  public static network.cow.environment.protocol.v1.UpdateAudioRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateAudioRequest>
      PARSER = new com.google.protobuf.AbstractParser<UpdateAudioRequest>() {
    @java.lang.Override
    public UpdateAudioRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UpdateAudioRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UpdateAudioRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UpdateAudioRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public network.cow.environment.protocol.v1.UpdateAudioRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

