// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: consumer_requests.proto

package network.cow.environment.protocol.v1;

public interface VectorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cow.environment.v1.Vector)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double x = 1;</code>
   * @return The x.
   */
  double getX();

  /**
   * <code>double y = 2;</code>
   * @return The y.
   */
  double getY();

  /**
   * <code>double z = 3;</code>
   * @return The z.
   */
  double getZ();
}
